"""Auto-generated W15 OSDK client for `customer`.

Source manifest: metadata.id=customer version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class CustomerRow(TypedDict, total=False):
    """Row shape for customer (dedicated columns + extension)."""
    id: str
    name: str
    email: str
    phone: str | None
    company: str | None
    status: str
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class CustomerClient:
    """HTTP client for `customer` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "customer"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> CustomerRow:
        """Fetch one customer instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/customer/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> CustomerRow:
        """Create a new customer instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[CustomerRow]:
        """List customer instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> CustomerRow:
        """Update fields on a customer instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a customer instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def archive_customer(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `archive_customer` (D-level=D2, hg_required=False).

        PL: Archiwizuje klienta i blokuje jego użycie w nowych aktywnych procesach operacyjnych. 
        EN: Archives the customer and prevents new active operational usage. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/customer/{instance_id}/actions/archive_customer",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def mark_active_customer(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `mark_active_customer` (D-level=D2, hg_required=False).

        PL: Oznacza klienta jako aktywnego i gotowego do dalszej obsługi operacyjnej. 
        EN: Marks the customer as active and ready for continued operational handling. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/customer/{instance_id}/actions/mark_active_customer",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

