"""Auto-generated W15 OSDK client for `idea`.

Source manifest: metadata.id=idea version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class IdeaRow(TypedDict, total=False):
    """Row shape for idea (dedicated columns + extension)."""
    id: str
    title: str
    description: str
    author: str
    status: str
    priority: int
    category: str | None
    domain: str | None
    tags: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class IdeaClient:
    """HTTP client for `idea` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "idea"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> IdeaRow:
        """Fetch one idea instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/idea/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> IdeaRow:
        """Create a new idea instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[IdeaRow]:
        """List idea instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> IdeaRow:
        """Update fields on a idea instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a idea instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def promote_to_project(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `promote_to_project` (D-level=D3, hg_required=False).

        PL: Promuje ideę do projektu roboczego po decyzji kwalifikacyjnej i ocenie ryzyka. 
        EN: Promotes the idea into a working project after qualification and risk review. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/idea/{instance_id}/actions/promote_to_project",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def archive_idea(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `archive_idea` (D-level=D2, hg_required=False).

        PL: Przenosi ideę do archiwum bez usuwania jej historii i danych kontekstowych. 
        EN: Moves the idea to archive without deleting its history and contextual data. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/idea/{instance_id}/actions/archive_idea",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def restore_idea(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `restore_idea` (D-level=D2, hg_required=False).

        PL: Przywraca ideę z archiwum do obiegu roboczego bez utraty śladu audytowego. 
        EN: Restores the idea from archive back into working circulation with audit continuity. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/idea/{instance_id}/actions/restore_idea",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def delete_soft(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `delete_soft` (D-level=D3, hg_required=True).

        PL: Oznacza ideę jako logicznie usuniętą bez fizycznego kasowania rekordu. 
        EN: Marks the idea as logically deleted without physically removing the record. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/idea/{instance_id}/actions/delete_soft",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def delete_hard(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `delete_hard` (D-level=D5, hg_required=True).

        PL: Uruchamia trwałe usunięcie idei i wymaga najwyższego poziomu kontroli człowieka. 
        EN: Initiates permanent deletion of the idea and requires the highest human control level. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/idea/{instance_id}/actions/delete_hard",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

