"""Auto-generated W15 OSDK client for `inspection`.

Source manifest: metadata.id=inspection version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class InspectionRow(TypedDict, total=False):
    """Row shape for inspection (dedicated columns + extension)."""
    id: str
    inspector: str
    inspected_at: str
    findings_count: int
    verdict: str
    notes: str | None
    vehicle_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class InspectionClient:
    """HTTP client for `inspection` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "inspection"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> InspectionRow:
        """Fetch one inspection instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/inspection/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> InspectionRow:
        """Create a new inspection instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[InspectionRow]:
        """List inspection instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> InspectionRow:
        """Update fields on a inspection instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a inspection instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def submit_inspection(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `submit_inspection` (D-level=D3, hg_required=True).

        PL: Składa inspekcję jako formalny raport i wymaga zatwierdzenia przez Human Gate. 
        EN: Submits the inspection as a formal report and requires Human Gate approval. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/inspection/{instance_id}/actions/submit_inspection",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def void_inspection(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `void_inspection` (D-level=D4, hg_required=True).

        PL: Unieważnia raport inspekcyjny w sytuacji błędu proceduralnego lub cofnięcia decyzji. 
        EN: Voids the inspection report in case of procedural error or decision rollback. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/inspection/{instance_id}/actions/void_inspection",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

