"""Auto-generated W15 OSDK client for `project`.

Source manifest: metadata.id=project version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class ProjectRow(TypedDict, total=False):
    """Row shape for project (dedicated columns + extension)."""
    id: str
    title: str
    status: str
    idea: str | None
    owner_id: str
    deadline: str | None
    budget_usd: float | None
    customer_id: str | None
    parent_idea_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class ProjectClient:
    """HTTP client for `project` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "project"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> ProjectRow:
        """Fetch one project instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/project/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> ProjectRow:
        """Create a new project instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[ProjectRow]:
        """List project instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> ProjectRow:
        """Update fields on a project instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a project instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def pause_project(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `pause_project` (D-level=D2, hg_required=False).

        PL: Wstrzymuje projekt bez usuwania jego kontekstu i zatrzymuje działania operacyjne do wznowienia. 
        EN: Pauses the project without deleting its context and halts operations until resumed. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/project/{instance_id}/actions/pause_project",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def resume_project(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `resume_project` (D-level=D2, hg_required=False).

        PL: Wznawia projekt po okresie pauzy i przywraca go do aktywnej realizacji. 
        EN: Resumes the project after a pause and returns it to active execution. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/project/{instance_id}/actions/resume_project",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def archive_project(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `archive_project` (D-level=D3, hg_required=True).

        PL: Archiwizuje projekt po zakończeniu lub decyzji governance i wymaga przejścia przez Human Gate. 
        EN: Archives the project after closure or governance decision and requires Human Gate approval. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/project/{instance_id}/actions/archive_project",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

