"""Auto-generated W15 OSDK client for `vehicle`.

Source manifest: metadata.id=vehicle version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class VehicleRow(TypedDict, total=False):
    """Row shape for vehicle (dedicated columns + extension)."""
    id: str
    vin: str
    plate: str
    make: str
    model: str
    year: int
    mileage_km: int | None
    owner_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class VehicleClient:
    """HTTP client for `vehicle` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "vehicle"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> VehicleRow:
        """Fetch one vehicle instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/vehicle/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> VehicleRow:
        """Create a new vehicle instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[VehicleRow]:
        """List vehicle instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> VehicleRow:
        """Update fields on a vehicle instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a vehicle instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def register_vehicle(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `register_vehicle` (D-level=D2, hg_required=False).

        PL: Rejestruje pojazd w runtime ontologii i emituje zdarzenie wejścia do rejestru. 
        EN: Registers the vehicle in the ontology runtime and emits an onboarding registry event. 
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/vehicle/{instance_id}/actions/register_vehicle",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

