"""Auto-generated W15 OSDK client for `w14_human_near_miss`.

Source manifest: metadata.id=w14_human_near_miss version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14HumanNearMissRow(TypedDict, total=False):
    """Row shape for w14_human_near_miss (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    blocked_successfully: bool
    operator_message_quality_score: float
    future_risk: str
    suggested_ui_improvement: str
    scenario_id: str | None
    error_injection_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14HumanNearMissClient:
    """HTTP client for `w14_human_near_miss` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_human_near_miss"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14HumanNearMissRow:
        """Fetch one w14_human_near_miss instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_human_near_miss/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14HumanNearMissRow:
        """Create a new w14_human_near_miss instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14HumanNearMissRow]:
        """List w14_human_near_miss instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14HumanNearMissRow:
        """Update fields on a w14_human_near_miss instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_human_near_miss instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def promote_human_near_miss(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `promote_human_near_miss` (D-level=D2, hg_required=False).

        PL: Promuje near miss do backlogu poprawy UX lub governance.
        EN: Promotes the near miss into UX or governance backlog.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_near_miss/{instance_id}/actions/promote_human_near_miss",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def dismiss_human_near_miss(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `dismiss_human_near_miss` (D-level=D3, hg_required=True).

        PL: Oznacza near miss jako zamknięty bez dalszych działań.
        EN: Dismisses the near miss with no further action.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_near_miss/{instance_id}/actions/dismiss_human_near_miss",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

