"""Auto-generated W15 OSDK client for `w14_simulation_evidence`.

Source manifest: metadata.id=w14_simulation_evidence version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14SimulationEvidenceRow(TypedDict, total=False):
    """Row shape for w14_simulation_evidence (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    simulation_ref: str
    trace_ref: str
    layer_executed: int
    branch_snapshot_hash: str
    sim_branch_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14SimulationEvidenceClient:
    """HTTP client for `w14_simulation_evidence` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_simulation_evidence"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14SimulationEvidenceRow:
        """Fetch one w14_simulation_evidence instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_simulation_evidence/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14SimulationEvidenceRow:
        """Create a new w14_simulation_evidence instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14SimulationEvidenceRow]:
        """List w14_simulation_evidence instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14SimulationEvidenceRow:
        """Update fields on a w14_simulation_evidence instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_simulation_evidence instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def seal_simulation_evidence(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `seal_simulation_evidence` (D-level=D4, hg_required=True).

        PL: Pieczętuje pakiet dowodowy do użycia w decyzjach releasowych.
        EN: Seals the evidence package for release decision use.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_simulation_evidence/{instance_id}/actions/seal_simulation_evidence",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def attach_simulation_evidence(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `attach_simulation_evidence` (D-level=D2, hg_required=False).

        PL: Dołącza dowód do bieżącej ścieżki walidacyjnej lub findingu.
        EN: Attaches the evidence to the current validation or finding path.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_simulation_evidence/{instance_id}/actions/attach_simulation_evidence",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

