"""Auto-generated W15 OSDK client for `w14_branch`.

Source manifest: metadata.id=w14_branch version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14BranchRow(TypedDict, total=False):
    """Row shape for w14_branch (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    branch_type: str
    parent_branch_ref: str | None
    project_ref: str
    sot_version: str
    masterplan_version: str
    state: str
    created_by: str
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14BranchClient:
    """HTTP client for `w14_branch` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_branch"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14BranchRow:
        """Fetch one w14_branch instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_branch/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14BranchRow:
        """Create a new w14_branch instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14BranchRow]:
        """List w14_branch instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14BranchRow:
        """Update fields on a w14_branch instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_branch instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def merge_branch(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `merge_branch` (D-level=D3, hg_required=True).

        PL: Oznacza gałąź jako scaloną po zakończeniu walidacji.
        EN: Marks the branch as merged after validation completes.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_branch/{instance_id}/actions/merge_branch",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def discard_branch(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `discard_branch` (D-level=D3, hg_required=True).

        PL: Odrzuca gałąź i blokuje jej dalsze użycie operacyjne.
        EN: Discards the branch and blocks further operational use.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_branch/{instance_id}/actions/discard_branch",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

