"""Auto-generated W15 OSDK client for `w14_test_suite`.

Source manifest: metadata.id=w14_test_suite version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14TestSuiteRow(TypedDict, total=False):
    """Row shape for w14_test_suite (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    name: str
    test_class: str
    enabled: bool
    case_count: int
    plan_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14TestSuiteClient:
    """HTTP client for `w14_test_suite` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_test_suite"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14TestSuiteRow:
        """Fetch one w14_test_suite instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_test_suite/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14TestSuiteRow:
        """Create a new w14_test_suite instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14TestSuiteRow]:
        """List w14_test_suite instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14TestSuiteRow:
        """Update fields on a w14_test_suite instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_test_suite instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def disable_test_suite(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `disable_test_suite` (D-level=D2, hg_required=False).

        PL: Wyłącza suite z bieżącego wykonania bez usuwania danych historycznych.
        EN: Disables the suite from current execution without deleting history.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_suite/{instance_id}/actions/disable_test_suite",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def enable_test_suite(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `enable_test_suite` (D-level=D2, hg_required=False).

        PL: Przywraca suite do aktywnego planu wykonania.
        EN: Restores the suite to the active execution plan.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_suite/{instance_id}/actions/enable_test_suite",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

