"""Auto-generated W15 OSDK client for `w14_release_candidate`.

Source manifest: metadata.id=w14_release_candidate version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14ReleaseCandidateRow(TypedDict, total=False):
    """Row shape for w14_release_candidate (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    project_ref: str
    gate_status: str
    evidence_pack: str | None
    unresolved_finding_count: int
    blocker_count: int
    branch_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14ReleaseCandidateClient:
    """HTTP client for `w14_release_candidate` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_release_candidate"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14ReleaseCandidateRow:
        """Fetch one w14_release_candidate instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_release_candidate/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14ReleaseCandidateRow:
        """Create a new w14_release_candidate instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14ReleaseCandidateRow]:
        """List w14_release_candidate instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14ReleaseCandidateRow:
        """Update fields on a w14_release_candidate instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_release_candidate instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def promote_release_candidate(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `promote_release_candidate` (D-level=D2, hg_required=False).

        PL: Promuje kandydaturę do gotowości produkcyjnej.
        EN: Promotes the candidate to production readiness.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_release_candidate/{instance_id}/actions/promote_release_candidate",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def rollback_release_candidate(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `rollback_release_candidate` (D-level=D4, hg_required=True).

        PL: Oznacza konieczność rollbacku po krytycznym sygnale ryzyka.
        EN: Marks the candidate as requiring rollback after a critical risk signal.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_release_candidate/{instance_id}/actions/rollback_release_candidate",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

