"""Auto-generated W15 OSDK client for `w14_patch_proposal`.

Source manifest: metadata.id=w14_patch_proposal version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14PatchProposalRow(TypedDict, total=False):
    """Row shape for w14_patch_proposal (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    status: str
    diff_lines_added: int
    diff_lines_removed: int
    proposed_by: str
    files_touched_count: int
    finding_id: str | None
    branch_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14PatchProposalClient:
    """HTTP client for `w14_patch_proposal` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_patch_proposal"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14PatchProposalRow:
        """Fetch one w14_patch_proposal instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_patch_proposal/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14PatchProposalRow:
        """Create a new w14_patch_proposal instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14PatchProposalRow]:
        """List w14_patch_proposal instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14PatchProposalRow:
        """Update fields on a w14_patch_proposal instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_patch_proposal instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def approve_patch_proposal(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `approve_patch_proposal` (D-level=D2, hg_required=False).

        PL: Zatwierdza propozycję poprawki do wdrożenia na branchu.
        EN: Approves the patch proposal for branch application.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_patch_proposal/{instance_id}/actions/approve_patch_proposal",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def revert_patch_proposal(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `revert_patch_proposal` (D-level=D3, hg_required=True).

        PL: Oznacza poprawkę jako cofniętą po negatywnym wyniku walidacji.
        EN: Marks the patch as reverted after failed validation.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_patch_proposal/{instance_id}/actions/revert_patch_proposal",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

