"""Auto-generated W15 OSDK client for `w14_regression_run`.

Source manifest: metadata.id=w14_regression_run version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14RegressionRunRow(TypedDict, total=False):
    """Row shape for w14_regression_run (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    status: str
    finding_id: str | None
    pre_fix_run_id: str | None
    post_fix_run_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14RegressionRunClient:
    """HTTP client for `w14_regression_run` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_regression_run"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14RegressionRunRow:
        """Fetch one w14_regression_run instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_regression_run/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14RegressionRunRow:
        """Create a new w14_regression_run instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14RegressionRunRow]:
        """List w14_regression_run instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14RegressionRunRow:
        """Update fields on a w14_regression_run instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_regression_run instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def mark_regression_passed(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `mark_regression_passed` (D-level=D2, hg_required=False).

        PL: Oznacza regresję jako zaliczoną po porównaniu obu przebiegów.
        EN: Marks the regression as passed after comparing both runs.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_regression_run/{instance_id}/actions/mark_regression_passed",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def mark_regression_failed(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `mark_regression_failed` (D-level=D2, hg_required=False).

        PL: Oznacza regresję jako nieudaną i emituje eskalację.
        EN: Marks the regression as failed and emits an escalation event.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_regression_run/{instance_id}/actions/mark_regression_failed",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

