"""Auto-generated W15 OSDK client for `w14_finding`.

Source manifest: metadata.id=w14_finding version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14FindingRow(TypedDict, total=False):
    """Row shape for w14_finding (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    severity: str
    r_status: str
    d_level: str
    title: str
    discovered_by: str
    ticket: str | None
    requirement_id: str | None
    test_run_id: str | None
    guardian_alert_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14FindingClient:
    """HTTP client for `w14_finding` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_finding"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14FindingRow:
        """Fetch one w14_finding instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_finding/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14FindingRow:
        """Create a new w14_finding instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14FindingRow]:
        """List w14_finding instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14FindingRow:
        """Update fields on a w14_finding instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_finding instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def triage_finding(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `triage_finding` (D-level=D2, hg_required=False).

        PL: Przenosi finding do stanu triage i rejestruje rozpoczęcie obsługi.
        EN: Moves the finding into triage and records handling start.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_finding/{instance_id}/actions/triage_finding",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def close_finding(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `close_finding` (D-level=D3, hg_required=True).

        PL: Zamyka finding po potwierdzeniu naprawy lub waiverze.
        EN: Closes the finding after fix verification or waiver.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_finding/{instance_id}/actions/close_finding",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

