"""Auto-generated W15 OSDK client for `w14_release_readiness_report`.

Source manifest: metadata.id=w14_release_readiness_report version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14ReleaseReadinessReportRow(TypedDict, total=False):
    """Row shape for w14_release_readiness_report (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    evidence_tier_used: str
    human_comprehension_score: float
    blocker_count: int
    warning_count: int
    recommendation_count: int
    release_candidate_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14ReleaseReadinessReportClient:
    """HTTP client for `w14_release_readiness_report` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_release_readiness_report"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14ReleaseReadinessReportRow:
        """Fetch one w14_release_readiness_report instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_release_readiness_report/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14ReleaseReadinessReportRow:
        """Create a new w14_release_readiness_report instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14ReleaseReadinessReportRow]:
        """List w14_release_readiness_report instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14ReleaseReadinessReportRow:
        """Update fields on a w14_release_readiness_report instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_release_readiness_report instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def publish_release_readiness_report(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `publish_release_readiness_report` (D-level=D2, hg_required=False).

        PL: Publikuje raport gotowości do wykorzystania przez operatora i council.
        EN: Publishes the readiness report for operator and council use.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_release_readiness_report/{instance_id}/actions/publish_release_readiness_report",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def revise_release_readiness_report(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `revise_release_readiness_report` (D-level=D2, hg_required=False).

        PL: Rejestruje rewizję raportu po nowych danych lub findingach.
        EN: Records a revision of the report after new data or findings.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_release_readiness_report/{instance_id}/actions/revise_release_readiness_report",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

