"""Auto-generated W15 OSDK client for `w14_human_scenario`.

Source manifest: metadata.id=w14_human_scenario version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14HumanScenarioRow(TypedDict, total=False):
    """Row shape for w14_human_scenario (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    domain: str
    difficulty: str
    workflow_step_count: int
    decision_point_count: int
    persona_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14HumanScenarioClient:
    """HTTP client for `w14_human_scenario` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_human_scenario"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14HumanScenarioRow:
        """Fetch one w14_human_scenario instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_human_scenario/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14HumanScenarioRow:
        """Create a new w14_human_scenario instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14HumanScenarioRow]:
        """List w14_human_scenario instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14HumanScenarioRow:
        """Update fields on a w14_human_scenario instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_human_scenario instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def promote_human_scenario(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `promote_human_scenario` (D-level=D2, hg_required=False).

        PL: Promuje scenariusz do obowiązkowego zestawu symulacyjnego.
        EN: Promotes the scenario to the mandatory simulation set.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_scenario/{instance_id}/actions/promote_human_scenario",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def retire_human_scenario(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `retire_human_scenario` (D-level=D3, hg_required=True).

        PL: Wycofuje scenariusz z aktywnej biblioteki testowej.
        EN: Retires the scenario from the active testing library.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_scenario/{instance_id}/actions/retire_human_scenario",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

