"""Auto-generated W15 OSDK client for `w14_test_charter`.

Source manifest: metadata.id=w14_test_charter version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14TestCharterRow(TypedDict, total=False):
    """Row shape for w14_test_charter (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    source_of_truth_version: str
    masterplan_version: str
    status: str
    hg_ticket: str | None
    council_session: str | None
    project_id: str | None
    idea_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14TestCharterClient:
    """HTTP client for `w14_test_charter` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_test_charter"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14TestCharterRow:
        """Fetch one w14_test_charter instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_test_charter/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14TestCharterRow:
        """Create a new w14_test_charter instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14TestCharterRow]:
        """List w14_test_charter instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14TestCharterRow:
        """Update fields on a w14_test_charter instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_test_charter instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def propose_charter(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `propose_charter` (D-level=D2, hg_required=False).

        PL: Przesuwa kartę do stanu proposed i zgłasza ją do przeglądu.
        EN: Moves the charter to proposed and submits it for review.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_charter/{instance_id}/actions/propose_charter",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def approve_charter(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `approve_charter` (D-level=D2, hg_required=False).

        PL: Zatwierdza kartę testów do użycia wykonawczego.
        EN: Approves the charter for execution use.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_charter/{instance_id}/actions/approve_charter",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def archive_charter(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `archive_charter` (D-level=D3, hg_required=True).

        PL: Archiwizuje kartę po zamknięciu cyklu testowego.
        EN: Archives the charter after the testing cycle closes.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_charter/{instance_id}/actions/archive_charter",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

