"""Auto-generated W15 OSDK client for `w14_human_error_injection`.

Source manifest: metadata.id=w14_human_error_injection version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14HumanErrorInjectionRow(TypedDict, total=False):
    """Row shape for w14_human_error_injection (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    error_class: str
    target_action: str
    timing: str
    context_label: str
    severity_if_allowed: str
    simulated_target_d_level: str
    action_d_level: str
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14HumanErrorInjectionClient:
    """HTTP client for `w14_human_error_injection` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_human_error_injection"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14HumanErrorInjectionRow:
        """Fetch one w14_human_error_injection instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_human_error_injection/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14HumanErrorInjectionRow:
        """Create a new w14_human_error_injection instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14HumanErrorInjectionRow]:
        """List w14_human_error_injection instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14HumanErrorInjectionRow:
        """Update fields on a w14_human_error_injection instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_human_error_injection instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def activate_human_error_injection(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `activate_human_error_injection` (D-level=D2, hg_required=False).

        PL: Włącza wzorzec błędu do bieżącej sesji symulacyjnej.
        EN: Activates the error pattern for the current simulation session.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_error_injection/{instance_id}/actions/activate_human_error_injection",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def retire_human_error_injection(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `retire_human_error_injection` (D-level=D3, hg_required=True).

        PL: Wycofuje wzorzec z biblioteki aktywnych testów.
        EN: Retires the pattern from the active testing library.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_error_injection/{instance_id}/actions/retire_human_error_injection",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

