"""Auto-generated W15 OSDK client for `w14_requirement`.

Source manifest: metadata.id=w14_requirement version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14RequirementRow(TypedDict, total=False):
    """Row shape for w14_requirement (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    source: str
    source_ref: str
    criticality: str
    test_required: bool
    description: str
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14RequirementClient:
    """HTTP client for `w14_requirement` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_requirement"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14RequirementRow:
        """Fetch one w14_requirement instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_requirement/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14RequirementRow:
        """Create a new w14_requirement instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14RequirementRow]:
        """List w14_requirement instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14RequirementRow:
        """Update fields on a w14_requirement instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_requirement instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def mark_requirement_covered(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `mark_requirement_covered` (D-level=D2, hg_required=False).

        PL: Oznacza wymaganie jako objęte aktywnym planem testów i emituje zdarzenie pokrycia.
        EN: Marks the requirement as covered by an active test plan and emits a coverage event.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_requirement/{instance_id}/actions/mark_requirement_covered",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def waive_requirement_test(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `waive_requirement_test` (D-level=D3, hg_required=True).

        PL: Wyłącza obowiązek testu dla wymagania po decyzji człowieka.
        EN: Disables the test obligation for the requirement after human decision.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_requirement/{instance_id}/actions/waive_requirement_test",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

