"""Auto-generated W15 OSDK client for `w14_loop_report`.

Source manifest: metadata.id=w14_loop_report version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14LoopReportRow(TypedDict, total=False):
    """Row shape for w14_loop_report (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    loop_type: str
    attempts_n: int
    similarity_score: float
    finding_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14LoopReportClient:
    """HTTP client for `w14_loop_report` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_loop_report"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14LoopReportRow:
        """Fetch one w14_loop_report instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_loop_report/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14LoopReportRow:
        """Create a new w14_loop_report instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14LoopReportRow]:
        """List w14_loop_report instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14LoopReportRow:
        """Update fields on a w14_loop_report instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_loop_report instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def escalate_loop_report(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `escalate_loop_report` (D-level=D3, hg_required=True).

        PL: Przekazuje raport pętli do decyzji człowieka lub councilu.
        EN: Escalates the loop report to human or council decision.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_loop_report/{instance_id}/actions/escalate_loop_report",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def acknowledge_loop_report(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `acknowledge_loop_report` (D-level=D2, hg_required=False).

        PL: Potwierdza odbiór raportu bez zmiany danych domenowych.
        EN: Acknowledges receipt of the report without changing domain data.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_loop_report/{instance_id}/actions/acknowledge_loop_report",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

