"""Auto-generated W15 OSDK client for `w14_human_decision_trace`.

Source manifest: metadata.id=w14_human_decision_trace version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14HumanDecisionTraceRow(TypedDict, total=False):
    """Row shape for w14_human_decision_trace (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    simulation_ref: str
    decision_count: int
    persona_id: str | None
    scenario_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14HumanDecisionTraceClient:
    """HTTP client for `w14_human_decision_trace` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_human_decision_trace"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14HumanDecisionTraceRow:
        """Fetch one w14_human_decision_trace instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_human_decision_trace/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14HumanDecisionTraceRow:
        """Create a new w14_human_decision_trace instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14HumanDecisionTraceRow]:
        """List w14_human_decision_trace instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14HumanDecisionTraceRow:
        """Update fields on a w14_human_decision_trace instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_human_decision_trace instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def seal_human_decision_trace(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `seal_human_decision_trace` (D-level=D4, hg_required=True).

        PL: Zamyka ślad decyzji do użycia jako dowód behawioralny.
        EN: Seals the decision trace for use as behavioral evidence.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_decision_trace/{instance_id}/actions/seal_human_decision_trace",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def attach_human_decision_trace(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `attach_human_decision_trace` (D-level=D2, hg_required=False).

        PL: Dołącza ślad do walidacji persony lub releasu.
        EN: Attaches the trace to persona or release validation.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_decision_trace/{instance_id}/actions/attach_human_decision_trace",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

