"""Auto-generated W15 OSDK client for `w14_test_plan`.

Source manifest: metadata.id=w14_test_plan version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14TestPlanRow(TypedDict, total=False):
    """Row shape for w14_test_plan (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    estimated_duration_s: int
    suite_count: int
    parallel_group_count: int
    charter_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14TestPlanClient:
    """HTTP client for `w14_test_plan` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_test_plan"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14TestPlanRow:
        """Fetch one w14_test_plan instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_test_plan/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14TestPlanRow:
        """Create a new w14_test_plan instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14TestPlanRow]:
        """List w14_test_plan instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14TestPlanRow:
        """Update fields on a w14_test_plan instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_test_plan instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def freeze_test_plan(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `freeze_test_plan` (D-level=D2, hg_required=False).

        PL: Zamyka plan do wykonania i emituje zdarzenie planistyczne.
        EN: Freezes the plan for execution and emits a planning event.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_plan/{instance_id}/actions/freeze_test_plan",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def resequence_test_plan(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `resequence_test_plan` (D-level=D2, hg_required=False).

        PL: Aktualizuje kolejność wykonania na podstawie nowych priorytetów.
        EN: Updates execution order based on revised priorities.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_plan/{instance_id}/actions/resequence_test_plan",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

