"""Auto-generated W15 OSDK client for `w14_human_persona`.

Source manifest: metadata.id=w14_human_persona version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14HumanPersonaRow(TypedDict, total=False):
    """Row shape for w14_human_persona (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    name: str
    capability_level: str
    error_proneness: float
    attention_span_min: int
    trust_in_ai_baseline: float
    risk_tolerance: str
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14HumanPersonaClient:
    """HTTP client for `w14_human_persona` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_human_persona"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14HumanPersonaRow:
        """Fetch one w14_human_persona instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_human_persona/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14HumanPersonaRow:
        """Create a new w14_human_persona instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14HumanPersonaRow]:
        """List w14_human_persona instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14HumanPersonaRow:
        """Update fields on a w14_human_persona instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_human_persona instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def retune_human_persona(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `retune_human_persona` (D-level=D2, hg_required=False).

        PL: Aktualizuje charakterystykę persony do kolejnej serii symulacji.
        EN: Retunes the persona profile for the next simulation series.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_persona/{instance_id}/actions/retune_human_persona",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def archive_human_persona(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `archive_human_persona` (D-level=D3, hg_required=True).

        PL: Archiwizuje personę po zakończeniu kampanii testowej.
        EN: Archives the persona after the test campaign ends.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_human_persona/{instance_id}/actions/archive_human_persona",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

