"""Auto-generated W15 OSDK client for `w14_simulation_contract`.

Source manifest: metadata.id=w14_simulation_contract version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14SimulationContractRow(TypedDict, total=False):
    """Row shape for w14_simulation_contract (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    simulation_ref: str
    sot_version: str
    masterplan_version: str
    source_project: str
    branch_id: str | None
    test_charter_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14SimulationContractClient:
    """HTTP client for `w14_simulation_contract` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_simulation_contract"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14SimulationContractRow:
        """Fetch one w14_simulation_contract instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_simulation_contract/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14SimulationContractRow:
        """Create a new w14_simulation_contract instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14SimulationContractRow]:
        """List w14_simulation_contract instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14SimulationContractRow:
        """Update fields on a w14_simulation_contract instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_simulation_contract instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def approve_simulation_contract(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `approve_simulation_contract` (D-level=D2, hg_required=False).

        PL: Zatwierdza kontrakt symulacji do wykonania w izolacji.
        EN: Approves the simulation contract for isolated execution.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_simulation_contract/{instance_id}/actions/approve_simulation_contract",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def abort_simulation_contract(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `abort_simulation_contract` (D-level=D3, hg_required=True).

        PL: Przerywa kontrakt symulacji z nieodwracalnym skutkiem operacyjnym.
        EN: Aborts the simulation contract with an irreversible operational effect.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_simulation_contract/{instance_id}/actions/abort_simulation_contract",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

