"""Auto-generated W15 OSDK client for `w14_simulation_branch`.

Source manifest: metadata.id=w14_simulation_branch version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14SimulationBranchRow(TypedDict, total=False):
    """Row shape for w14_simulation_branch (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    state: str
    discard_reason: str | None
    snapshot_db_path: str | None
    parent_branch_id: str | None
    contract_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14SimulationBranchClient:
    """HTTP client for `w14_simulation_branch` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_simulation_branch"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14SimulationBranchRow:
        """Fetch one w14_simulation_branch instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_simulation_branch/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14SimulationBranchRow:
        """Create a new w14_simulation_branch instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14SimulationBranchRow]:
        """List w14_simulation_branch instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14SimulationBranchRow:
        """Update fields on a w14_simulation_branch instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_simulation_branch instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def discard_simulation_branch(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `discard_simulation_branch` (D-level=D3, hg_required=True).

        PL: Odrzuca gałąź symulacyjną po zakończeniu eksperymentu.
        EN: Discards the simulation branch after the experiment completes.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_simulation_branch/{instance_id}/actions/discard_simulation_branch",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def reopen_simulation_branch(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `reopen_simulation_branch` (D-level=D2, hg_required=False).

        PL: Przywraca gałąź do stanu open dla powtórnej walidacji.
        EN: Returns the branch to open for repeated validation.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_simulation_branch/{instance_id}/actions/reopen_simulation_branch",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

