"""Auto-generated W15 OSDK client for `w14_test_run`.

Source manifest: metadata.id=w14_test_run version=v1.0
Generated by sylion.aeis_v2.ontology.osdk_gen.

DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.
"""
from __future__ import annotations

from typing import Any, TypedDict

import httpx


class W14TestRunRow(TypedDict, total=False):
    """Row shape for w14_test_run (dedicated columns + extension)."""
    id: str
    legacy_w14_id: str
    status: str
    duration_ms: int | None
    cost_usd: float
    trace_ref: str
    evidence_pack: str | None
    suite_id: str | None
    case_id: str | None
    branch_id: str | None
    charter_id: str | None
    extension: dict[str, Any]
    created_at: str
    updated_at: str


class W14TestRunClient:
    """HTTP client for `w14_test_run` ontology type."""

    def __init__(self, base_url: str = "http://127.0.0.1:8000",
                  api_key: str | None = None,
                  timeout: float = 10.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.type_id = "w14_test_run"
        self.timeout = timeout
        self._headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            self._headers["Authorization"] = f"Bearer {api_key}"

    def get(self, instance_id: str) -> W14TestRunRow:
        """Fetch one w14_test_run instance by id."""
        with httpx.Client(timeout=self.timeout) as c:
            r = c.get(
                f"{self.base_url}/api/v1/ontology/w14_test_run/{instance_id}",
                headers=self._headers,
            )
            r.raise_for_status()
            return r.json()

    def create(self, **fields: Any) -> W14TestRunRow:
        """Create a new w14_test_run instance.

        Phase 0: returns NotImplementedError until W15 G2 instance
        endpoints land. Stub kept so consumers can import.
        """
        raise NotImplementedError(
            "create({fields}) requires W15 G2 instance endpoints"
        )

    def list(self, *, limit: int = 50, offset: int = 0) -> list[W14TestRunRow]:
        """List w14_test_run instances."""
        raise NotImplementedError(
            "list() requires W15 G2 instance endpoints"
        )

    def update(self, instance_id: str, **fields: Any) -> W14TestRunRow:
        """Update fields on a w14_test_run instance."""
        raise NotImplementedError("update() requires W15 G2")

    def delete(self, instance_id: str) -> bool:
        """Soft-delete a w14_test_run instance."""
        raise NotImplementedError("delete() requires W15 G2")

    def finish_test_run(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `finish_test_run` (D-level=D2, hg_required=False).

        PL: Kończy wykonanie testu i oznacza wynik jako passed.
        EN: Finishes the test run and marks the outcome as passed.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_run/{instance_id}/actions/finish_test_run",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def fail_test_run(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `fail_test_run` (D-level=D2, hg_required=False).

        PL: Kończy wykonanie testu z wynikiem failed.
        EN: Ends the test run with a failed status.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_run/{instance_id}/actions/fail_test_run",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

    def abort_test_run(self, instance_id: str, **payload: Any) -> dict[str, Any]:
        """Action `abort_test_run` (D-level=D3, hg_required=True).

        PL: Przerywa aktywne wykonanie z nieodwracalnym skutkiem operacyjnym.
        EN: Aborts an active run with an irreversible operational side effect.
        """
        with httpx.Client(timeout=self.timeout) as c:
            r = c.post(
                f"{self.base_url}/api/v1/ontology/w14_test_run/{instance_id}/actions/abort_test_run",
                headers=self._headers, json=payload,
            )
            r.raise_for_status()
            return r.json()

