"""Comprehensive RBAC matrix verification for SYLION AEIS v2 REST surface.

Goal: every v2 REST endpoint is exercised through two role contexts so we
detect regressions where a new route either (a) crashes the RBAC middleware
(``500``) or (b) is silently exempted from auth.

Two parametrized regression locks per route:

1. **No role header** — the request is sent without ``X-Sylion-Role`` /
   bearer token. The contract: never ``500``. In the default test
   environment ``SYLION_RBAC_DISABLED=1`` (set globally by
   ``tests/conftest.py``) so the actual response is usually ``200``/``4xx``;
   what matters is that the middleware does not blow up.

2. **Operator role** — same request with ``X-Sylion-Role: operator`` and
   ``Authorization: Bearer dev-bypass``. The contract: ``200`` or any
   ``4xx`` (validation, missing body, 404 for empty registries, etc.) but
   NEVER ``5xx``. A ``500`` from a route through the v2 plane means a route
   handler raised an unhandled exception in the happy-path smoke shape.

Skipped paths:

- Path templates with ``{...}`` placeholders — they need real ids and are
  covered by their own integration tests.
- ``/api/v1/terminal/stream`` — SSE streaming endpoint that holds the
  connection open forever; would deadlock the synchronous TestClient.
- ``/api/v1/terminal/_dev/inject_event`` — dev-only injection endpoint,
  covered by the terminal-suite integration tests.

The catalogue ``V2_ROUTES`` was generated by walking the v2 routers
(``federation_routes``, ``ontology_routes``, ``terminal_routes``,
``role_catalog_routes``, ``apps_routes``, ``policy_routes``,
``cron_routes``). The bookkeeping test
``test_v2_routes_catalogue_is_complete`` re-walks the routers at runtime
and skips with a clear message when somebody adds a new endpoint without
adding it here, so the matrix stays in sync without being a hard blocker
on new routes.
"""
from __future__ import annotations

from typing import Any

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from sylion.api.apps_routes import router as apps_router
from sylion.api.cron_routes import router as cron_router
from sylion.api.federation_routes import router as federation_router
from sylion.api.ontology_routes import router as ontology_router
from sylion.api.policy_routes import router as policy_router
from sylion.api.role_catalog_routes import router as role_catalog_router
from sylion.api.terminal_routes import router as terminal_router

# ---------------------------------------------------------------------------
# Routers under test (the v2 plane)
# ---------------------------------------------------------------------------
#
# Order doesn't matter — TestClient resolves the longest matching path
# anyway. This list lives next to the catalogue so the bookkeeping test can
# re-walk every v2 router at runtime.
V2_ROUTERS = (
    apps_router,
    cron_router,
    federation_router,
    ontology_router,
    policy_router,
    role_catalog_router,
    terminal_router,
)


# ---------------------------------------------------------------------------
# V2 endpoint catalogue
# ---------------------------------------------------------------------------
#
# Each entry: (HTTP_METHOD, PATH, REQUIRED_ROLE, BODY).
#
# - ``REQUIRED_ROLE`` documents the canonical role tier we expect the
#   endpoint to demand. ``"operator"`` is the v2 default; the rare public
#   endpoint (none today — even ``/health`` requires operator under the
#   federation/policy/apps planes) is marked ``None``.
# - ``BODY`` is the smoke-shape payload to send for POST/PUT/PATCH. ``None``
#   means "send no body" — the route either accepts it (no-body endpoints)
#   or returns 422 (validation error), both of which are 4xx and pass the
#   "no 5xx" contract.
#
# 65 endpoints across 7 routers as of 2026-04-27. ``test_v2_routes_catalogue
# _is_complete`` re-walks the routers at runtime and warns when this list
# falls out of sync.
V2_ROUTES: list[tuple[str, str, str, Any]] = [
    # --- W16 Apps Builder Plane ------------------------------------------
    ("GET", "/api/v1/apps", "operator", None),
    ("GET", "/api/v1/apps/health", "operator", None),
    ("POST", "/api/v1/apps/match-idea", "operator", {"idea_text": "smoke test idea"}),
    ("GET", "/api/v1/apps/{app_id}", "operator", None),

    # --- v2 cron-mode metrics widget -------------------------------------
    ("GET", "/api/v1/cron/status", "operator", None),

    # --- W17 Compute Provider Federation ---------------------------------
    ("GET", "/api/v1/federation/costs/aggregate", "operator", None),
    ("POST", "/api/v1/federation/costs/apply-pg-ddl", "operator", {"dry_run": True}),
    ("GET", "/api/v1/federation/costs/recent", "operator", None),
    ("POST", "/api/v1/federation/costs/record", "operator", {"model": "smoke"}),
    ("POST", "/api/v1/federation/costs/refresh-mv", "operator", {"concurrently": True}),
    ("POST", "/api/v1/federation/costs/refresher/start", "operator", {}),
    ("GET", "/api/v1/federation/costs/refresher/stats", "operator", None),
    ("POST", "/api/v1/federation/costs/refresher/stop", "operator", None),
    ("GET", "/api/v1/federation/health", "operator", None),
    ("GET", "/api/v1/federation/nodes", "operator", None),
    ("POST", "/api/v1/federation/nodes", "operator", {
        "name": "rbac-smoke-node",
        "kind": "compute_provider",
        "status": "online",
        "base_url": "http://localhost:9999",
        "locality": "local",
        "capacity_score": 1.0,
    }),
    ("GET", "/api/v1/federation/nodes/active", "operator", None),
    ("DELETE", "/api/v1/federation/nodes/{node_id}", "operator", None),
    ("POST", "/api/v1/federation/nodes/{node_id}/heartbeat", "operator", {"status": "online"}),
    ("POST", "/api/v1/federation/route", "operator", {"model_id": "smoke", "privacy_level": "any"}),

    # --- W15 Ontology Runtime Plane --------------------------------------
    ("POST", "/api/v1/ontology/apply-all", "operator", None),
    ("GET", "/api/v1/ontology/health", "operator", None),
    ("POST", "/api/v1/ontology/migration/w14/apply", "operator", {"sqlite_path": "/dev/null/missing"}),
    ("POST", "/api/v1/ontology/migration/w14/preview", "operator", None),
    ("POST", "/api/v1/ontology/regenerate-osdk", "operator", None),
    ("POST", "/api/v1/ontology/regenerate-osdk-ts", "operator", None),
    ("POST", "/api/v1/ontology/reload", "operator", None),
    ("GET", "/api/v1/ontology/types", "operator", None),
    ("GET", "/api/v1/ontology/types/{type_id}", "operator", None),
    ("GET", "/api/v1/ontology/types/{type_id}/actions", "operator", None),
    ("POST", "/api/v1/ontology/types/{type_id}/apply", "operator", None),
    ("GET", "/api/v1/ontology/types/{type_id}/ddl", "operator", None),
    ("GET", "/api/v1/ontology/types/{type_id}/osdk", "operator", None),
    ("GET", "/api/v1/ontology/types/{type_id}/osdk-ts", "operator", None),

    # --- W19 Policy / Security Plane -------------------------------------
    ("POST", "/api/v1/policy/evaluate", "operator", {"policy_id": "data_locality_eu"}),
    ("GET", "/api/v1/policy/health", "operator", None),
    ("GET", "/api/v1/policy/policies", "operator", None),
    ("GET", "/api/v1/policy/policies/{policy_id}", "operator", None),

    # --- W7 Role Catalog (Skills Registry extension) ---------------------
    ("GET", "/api/v1/role-catalog", "operator", None),
    ("GET", "/api/v1/role-catalog/by-capability/{capability_id}", "operator", None),
    ("GET", "/api/v1/role-catalog/capabilities", "operator", None),
    ("GET", "/api/v1/role-catalog/categories", "operator", None),
    ("GET", "/api/v1/role-catalog/category/{category}", "operator", None),
    ("GET", "/api/v1/role-catalog/health", "operator", None),
    ("POST", "/api/v1/role-catalog/hybrid-match", "operator", {"task_description": "smoke"}),
    ("POST", "/api/v1/role-catalog/match", "operator", {"task": "smoke"}),
    ("POST", "/api/v1/role-catalog/match-task", "operator", {"required_capabilities": []}),
    ("GET", "/api/v1/role-catalog/{role_id}", "operator", None),

    # --- W18 Operator Terminal Plane -------------------------------------
    ("POST", "/api/v1/terminal/_dev/inject_event", "operator", {}),
    ("GET", "/api/v1/terminal/commands", "operator", None),
    ("POST", "/api/v1/terminal/exec", "operator", {"line": "/status"}),
    ("GET", "/api/v1/terminal/health", "operator", None),
    ("GET", "/api/v1/terminal/replay/days", "operator", None),
    ("GET", "/api/v1/terminal/replay/slice", "operator", None),
    ("GET", "/api/v1/terminal/sessions", "operator", None),
    ("POST", "/api/v1/terminal/sessions", "operator", {"title": "rbac smoke"}),
    ("GET", "/api/v1/terminal/sessions/{session_id}", "operator", None),
    ("POST", "/api/v1/terminal/sessions/{session_id}/cancel", "operator", None),
    ("POST", "/api/v1/terminal/sessions/{session_id}/close", "operator", None),
    ("POST", "/api/v1/terminal/sessions/{session_id}/tasks", "operator", {"title": "t"}),
    ("PATCH", "/api/v1/terminal/sessions/{session_id}/tasks/{task_id}", "operator", {}),
    ("POST", "/api/v1/terminal/sessions/{session_id}/tasks/{task_id}/pause", "operator", None),
    ("POST", "/api/v1/terminal/sessions/{session_id}/tasks/{task_id}/resume", "operator", None),
    ("POST", "/api/v1/terminal/sessions/{session_id}/tasks/{task_id}/skip", "operator", None),
    ("GET", "/api/v1/terminal/stream", "operator", None),
]


# Endpoints that MUST be skipped at request time even when they have a
# concrete (non-template) path. Each entry is a (method, path) pair.
#
# - ``GET /api/v1/terminal/stream`` is a Server-Sent-Events endpoint that
#   never returns to the synchronous TestClient. We still keep it in the
#   catalogue so ``test_v2_routes_catalogue_is_complete`` notices when it
#   gets removed/renamed, but the smoke matrix skips dispatch.
# - ``POST /api/v1/terminal/_dev/inject_event`` is a dev-only convenience
#   endpoint covered by ``test_terminal_intervention.py``; we skip it from
#   the matrix (the brief explicitly excludes ``/_dev/*``).
_RUNTIME_SKIP: frozenset[tuple[str, str]] = frozenset({
    ("GET", "/api/v1/terminal/stream"),
    ("POST", "/api/v1/terminal/_dev/inject_event"),
})


# ---------------------------------------------------------------------------
# Test fixture
# ---------------------------------------------------------------------------


def _build_app() -> FastAPI:
    """Build a lightweight FastAPI with only the v2 routers mounted.

    We intentionally do NOT use ``sylion.api.app:app`` here — its lifespan
    seeds RBAC roles, key vault, observability, etc. The matrix only needs
    to verify "no 500 from the route handler", which is decoupled from
    bootstrap state. Mounting the bare routers keeps the suite < 1s.
    """
    api = FastAPI()
    for router in V2_ROUTERS:
        api.include_router(router)
    return api


@pytest.fixture(scope="module")
def client() -> TestClient:
    """One TestClient per module — mount cost is paid once."""
    return TestClient(_build_app())


# ---------------------------------------------------------------------------
# Bookkeeping — keep V2_ROUTES in sync with the actual router topology
# ---------------------------------------------------------------------------


def _enumerate_router_routes(routers: tuple) -> set[tuple[str, str]]:
    """Walk v2 routers and yield (method, path) for every non-CORS verb."""
    seen: set[tuple[str, str]] = set()
    for router in routers:
        for route in router.routes:
            path = getattr(route, "path", None)
            methods = getattr(route, "methods", None)
            if not path or not methods:
                continue
            for method in methods:
                if method in {"HEAD", "OPTIONS"}:
                    continue
                seen.add((method, path))
    return seen


def test_v2_routes_catalogue_is_complete():
    """Every (method, path) on a v2 router has a V2_ROUTES entry.

    Informational rather than blocking: when the catalogue falls behind
    a new endpoint, we ``pytest.skip`` with a precise diff so the operator
    can update this file in seconds. Hard-failing here would block every
    PR that adds a new v2 endpoint.
    """
    discovered = _enumerate_router_routes(V2_ROUTERS)
    cataloged = {(m, p) for m, p, _, _ in V2_ROUTES}
    missing = discovered - cataloged
    extra = cataloged - discovered
    if missing or extra:
        pytest.skip(
            f"V2_ROUTES catalogue out of sync — "
            f"missing={sorted(missing)} extra={sorted(extra)}"
        )


# ---------------------------------------------------------------------------
# RBAC matrix — every catalogued route gets two role-axis test instances.
# ---------------------------------------------------------------------------


def _idfn(case: tuple[str, str, str, Any]) -> str:
    """Build a readable parametrize id: ``GET /api/v1/apps``."""
    method, path, _role, _body = case
    return f"{method} {path}"


_OPERATOR_CASES = [c for c in V2_ROUTES if c[2] == "operator"]


@pytest.mark.parametrize("case", _OPERATOR_CASES, ids=_idfn)
def test_v2_route_no_role_header_never_500(client: TestClient, case):
    """No role header → response must not be ``5xx``.

    In the default test env ``SYLION_RBAC_DISABLED=1`` is set globally
    (see ``tests/conftest.py``) so the request usually returns ``200``
    / ``4xx``. The KEY contract: the RBAC + auth middleware path never
    raises an unhandled exception, which would surface as ``500``.

    Path templates and SSE/dev endpoints are skipped — those need
    integration-level setup (real ids, async loop drain) that this
    fast smoke suite intentionally avoids.
    """
    method, path, _role, body = case
    if "{" in path:
        pytest.skip(f"path template — covered by integration tests: {path}")
    if (method, path) in _RUNTIME_SKIP:
        pytest.skip(f"runtime-skipped (SSE/dev): {method} {path}")

    resp = client.request(method, path, json=body)

    assert resp.status_code != 500, (
        f"{method} {path}: middleware/handler raised 500 without role header — "
        f"body={resp.text[:200]}"
    )
    # Tighter sanity: no 5xx at all.
    assert resp.status_code < 500, (
        f"{method} {path}: unexpected 5xx without role: {resp.status_code} — "
        f"{resp.text[:200]}"
    )


@pytest.mark.parametrize("case", _OPERATOR_CASES, ids=_idfn)
def test_v2_route_with_operator_role_returns_2xx_or_4xx(client: TestClient, case):
    """With ``X-Sylion-Role: operator`` + bearer token → never ``5xx``.

    Concrete codes vary by endpoint: ``200`` for healthy GETs, ``404`` when
    the resource is missing, ``422`` when the smoke body is incomplete,
    ``400`` when domain validation rejects the smoke values. Anything in
    ``200..499`` is acceptable — the matrix only catches ``5xx`` regressions
    where a route blows up in the operator-happy-path.
    """
    method, path, _role, body = case
    if "{" in path:
        pytest.skip(f"path template — covered by integration tests: {path}")
    if (method, path) in _RUNTIME_SKIP:
        pytest.skip(f"runtime-skipped (SSE/dev): {method} {path}")

    headers = {
        "X-Sylion-Role": "operator",
        "Authorization": "Bearer dev-bypass",
    }
    resp = client.request(method, path, json=body, headers=headers)

    assert resp.status_code != 500, (
        f"{method} {path}: handler raised 500 with operator role — "
        f"{resp.text[:200]}"
    )
    assert 200 <= resp.status_code < 500, (
        f"{method} {path}: unexpected status with operator role: "
        f"{resp.status_code} — {resp.text[:200]}"
    )
