"""W15 G2 OSDK auto-generator -- manifest -> typed Python client.

For each manifest, emits a Python module under `_osdk/<type_id>.py` with:
- TypedDict for the row shape (dedicated_columns + extension)
- Per-action method stubs that POST /api/v1/ontology/{type_id}/{instance_id}/actions/{action_id}
- CRUD methods: create, get, update, delete, list, search

Phase 0 limitations (G2 closes them in next iteration):
- HTTP-based client only (no direct PG access)
- Returns dicts not full pydantic models
- Action invocation stubs raise NotImplementedError until W15 G3
- search() does naive substring filter on title only
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from sylion.aeis_v2.ontology.manifest import (
    DedicatedColumn,
    ObjectTypeManifest,
)


_PG_TO_PY: dict[str, str] = {
    "text": "str",
    "integer": "int",
    "bigint": "int",
    "boolean": "bool",
    "timestamptz": "str",     # ISO format string in JSON; G3 will use datetime
    "numeric": "float",
    "uuid": "str",
    "date": "str",
    "jsonb": "dict[str, Any]",
    "bytea": "bytes",
}


def _py_type(col: DedicatedColumn) -> str:
    base = _PG_TO_PY.get(col.type, "Any")
    return base + " | None" if col.nullable else base


def _camelcase(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("_"))


@dataclass
class GeneratedModule:
    type_id: str
    module_name: str          # e.g. "customer"
    code: str                 # full Python source
    line_count: int


def generate_module(manifest: ObjectTypeManifest) -> GeneratedModule:
    """Return Python source for a manifest's OSDK client module."""
    meta = manifest.metadata
    spec = manifest.spec
    type_id = meta.id
    klass = _camelcase(type_id) + "Client"
    row_class = _camelcase(type_id) + "Row"

    cols = spec.dedicated_columns
    relations = spec.relations
    actions = spec.actions

    # --- Header
    lines: list[str] = [
        f'"""Auto-generated W15 OSDK client for `{type_id}`.',
        '',
        f'Source manifest: metadata.id={type_id} version={meta.version}',
        f'Generated by sylion.aeis_v2.ontology.osdk_gen.',
        '',
        'DO NOT EDIT -- regenerate via POST /api/v1/ontology/regenerate-osdk.',
        '"""',
        'from __future__ import annotations',
        '',
        'from typing import Any, TypedDict',
        '',
        'import httpx',
        '',
        '',
    ]

    # --- TypedDict for row shape
    lines.append(f'class {row_class}(TypedDict, total=False):')
    lines.append(f'    """Row shape for {type_id} (dedicated columns + extension)."""')
    lines.append('    id: str')
    for c in cols:
        lines.append(f'    {c.name}: {_py_type(c)}')
    for r in relations:
        if r.cardinality in {"many_to_one", "one_to_one"}:
            lines.append(f'    {r.name}_id: str | None')
    lines.append("    extension: dict[str, Any]")
    lines.append("    created_at: str")
    lines.append("    updated_at: str")
    lines.append('')
    lines.append('')

    # --- Client class
    lines.append(f'class {klass}:')
    lines.append(f'    """HTTP client for `{type_id}` ontology type."""')
    lines.append('')
    lines.append('    def __init__(self, base_url: str = "http://127.0.0.1:8000",')
    lines.append('                  api_key: str | None = None,')
    lines.append('                  timeout: float = 10.0) -> None:')
    lines.append('        self.base_url = base_url.rstrip("/")')
    lines.append(f'        self.type_id = "{type_id}"')
    lines.append('        self.timeout = timeout')
    lines.append('        self._headers: dict[str, str] = {"Content-Type": "application/json"}')
    lines.append('        if api_key:')
    lines.append('            self._headers["Authorization"] = f"Bearer {api_key}"')
    lines.append('')

    # --- CRUD methods
    lines.append(f'    def get(self, instance_id: str) -> {row_class}:')
    lines.append(f'        """Fetch one {type_id} instance by id."""')
    lines.append('        with httpx.Client(timeout=self.timeout) as c:')
    lines.append('            r = c.get(')
    lines.append(f'                f"{{self.base_url}}/api/v1/ontology/{type_id}/{{instance_id}}",')
    lines.append('                headers=self._headers,')
    lines.append('            )')
    lines.append('            r.raise_for_status()')
    lines.append('            return r.json()')
    lines.append('')

    lines.append(f'    def create(self, **fields: Any) -> {row_class}:')
    lines.append(f'        """Create a new {type_id} instance.')
    lines.append('')
    lines.append('        Phase 0: returns NotImplementedError until W15 G2 instance')
    lines.append('        endpoints land. Stub kept so consumers can import.')
    lines.append('        """')
    lines.append('        raise NotImplementedError(')
    lines.append(f'            "create({{fields}}) requires W15 G2 instance endpoints"')
    lines.append('        )')
    lines.append('')

    lines.append(f'    def list(self, *, limit: int = 50, offset: int = 0) -> list[{row_class}]:')
    lines.append(f'        """List {type_id} instances."""')
    lines.append('        raise NotImplementedError(')
    lines.append('            "list() requires W15 G2 instance endpoints"')
    lines.append('        )')
    lines.append('')

    lines.append('    def update(self, instance_id: str, **fields: Any) -> ' + row_class + ':')
    lines.append(f'        """Update fields on a {type_id} instance."""')
    lines.append('        raise NotImplementedError("update() requires W15 G2")')
    lines.append('')

    lines.append('    def delete(self, instance_id: str) -> bool:')
    lines.append(f'        """Soft-delete a {type_id} instance."""')
    lines.append('        raise NotImplementedError("delete() requires W15 G2")')
    lines.append('')

    # --- Action methods
    for action in actions:
        method_name = re.sub(r"[^a-z0-9_]", "_", action.id.lower())
        lines.append(f'    def {method_name}(self, instance_id: str, **payload: Any) -> dict[str, Any]:')
        lines.append(f'        """Action `{action.id}` (D-level={action.d_level}, hg_required={action.hg_required}).')
        lines.append('')
        if action.description_pl:
            # Sanitize: take first 200 chars, remove newlines and triple quotes.
            desc_pl = action.description_pl[:200].replace('\n', ' ').replace('"""', '')
            lines.append(f'        PL: {desc_pl}')
        if action.description_en:
            desc_en = action.description_en[:200].replace('\n', ' ').replace('"""', '')
            lines.append(f'        EN: {desc_en}')
        lines.append('        """')
        lines.append('        with httpx.Client(timeout=self.timeout) as c:')
        lines.append('            r = c.post(')
        lines.append(f'                f"{{self.base_url}}/api/v1/ontology/{type_id}/'
                     f'{{instance_id}}/actions/{action.id}",')
        lines.append('                headers=self._headers, json=payload,')
        lines.append('            )')
        lines.append('            r.raise_for_status()')
        lines.append('            return r.json()')
        lines.append('')

    code = "\n".join(lines) + "\n"
    return GeneratedModule(type_id=type_id, module_name=type_id, code=code, line_count=len(lines))


def write_osdk_module(manifest: ObjectTypeManifest, target_dir: str) -> str:
    """Write generated module to disk. Returns path to written file."""
    from pathlib import Path
    out = Path(target_dir)
    out.mkdir(parents=True, exist_ok=True)
    init_py = out / "__init__.py"
    if not init_py.exists():
        init_py.write_text(
            '"""Auto-generated OSDK clients. Regenerate via osdk_gen."""\n',
            encoding="utf-8",
        )
    mod = generate_module(manifest)
    target = out / f"{mod.type_id}.py"
    target.write_text(mod.code, encoding="utf-8")
    return str(target)


def regenerate_all(target_dir: str | None = None) -> list[str]:
    """Regenerate every loaded manifest's OSDK module. Returns list of paths written."""
    from pathlib import Path
    from sylion.aeis_v2.ontology.registry import get_registry
    if target_dir is None:
        target_dir = str(Path(__file__).parent / "_osdk")
    reg = get_registry()
    written: list[str] = []
    for tid in reg.list_ids():
        manifest = reg.get(tid)
        if manifest is None:
            continue
        written.append(write_osdk_module(manifest, target_dir))
    return written
