#!/usr/bin/env python3
"""
SYLION BookGuardian — Read-Only Protection for Księga

Księga SYLION 3.4 FIXED is the normative document for the entire pipeline.
BookGuardian ensures it is NEVER modified, mutated, or drifted by any agent.

Architecture:
  1. On pipeline start: compute and store baseline SHA-256 of Księga file
  2. On each stage boundary: re-hash and compare
  3. On mismatch: HALT pipeline + CRITICAL escalation to Human Gate
  4. Optional cron mode: check every N seconds (standalone watchdog)

Integration:
  - orchestrator.py: init_book_guardian() in pipeline init, check_ksiega() at stage boundaries
  - supervisor.py: GateLevel.CRITICAL escalation on drift
  - agents.yaml: book_guardian agent definition

BookGuardian NEVER:
  - Modifies Księga
  - Suggests changes
  - Generates new requirements
  - Auto-approves without explicit human input

INVARIANT — Source of Truth hierarchy:
  - Księga SYLION 3.4 FIXED = normative baseline (read-only, BookGuardian protected)
  - requirements.json = DERIVED ARTIFACT (generated by ksiega_analyst, Stage 1)
    Requirements.json is a working extraction, not a source of truth.
    If Księga and requirements.json conflict, Księga wins.
    BookGuardian protects Księga; it does NOT protect requirements.json.
"""

from __future__ import annotations

import hashlib
import json
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol

logger = logging.getLogger("book_guardian")

_HASH_BUF_SIZE = 65536


# ---------------------------------------------------------------------------
# Protocols (loose coupling)
# ---------------------------------------------------------------------------

class HumanGateProtocol(Protocol):
    """Minimal interface from supervisor.HumanGate."""
    def request_approval(self, request: Any) -> Any: ...


class ContextPersistenceProtocol(Protocol):
    """Minimal interface from loop_guard.ContextPersistence."""
    def record_event(
        self, event_type: Any, agent_id: str,
        description: str, details: dict[str, Any] | None = None,
    ) -> None: ...


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class KsiegaSnapshot:
    """Immutable snapshot of Księga file at a point in time."""
    file_path: str
    sha256: str
    size_bytes: int
    mtime: float
    exists: bool
    snapshot_time: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "file_path": self.file_path,
            "sha256": self.sha256,
            "size_bytes": self.size_bytes,
            "mtime": self.mtime,
            "exists": self.exists,
            "snapshot_time": self.snapshot_time.isoformat(),
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> KsiegaSnapshot:
        d = dict(d)
        d["snapshot_time"] = datetime.fromisoformat(d["snapshot_time"])
        return cls(**d)


@dataclass
class DriftReport:
    """Report generated when Księga drift is detected."""
    baseline: KsiegaSnapshot
    current: KsiegaSnapshot
    drift_detected: bool
    description: str
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "baseline": self.baseline.to_dict(),
            "current": self.current.to_dict(),
            "drift_detected": self.drift_detected,
            "description": self.description,
            "timestamp": self.timestamp.isoformat(),
        }


# ---------------------------------------------------------------------------
# BookGuardian — core class
# ---------------------------------------------------------------------------

class BookGuardian:
    """Read-only guardian for Księga SYLION.

    Lifecycle:
      1. init → compute baseline SHA-256
      2. check() → re-hash and compare (call at stage boundaries)
      3. on drift → CRITICAL alert + halt

    Usage in orchestrator:
        from book_guardian import BookGuardian

        guardian = BookGuardian(
            ksiega_path=cfg.ksiega_path,
            human_gate=human_gate,
            log_dir=results_dir / "book_guardian",
        )

        # At each stage boundary:
        if not guardian.check():
            # Pipeline halted — drift detected
            sys.exit(1)
    """

    AGENT_ID = "book_guardian"

    def __init__(
        self,
        ksiega_path: Path,
        human_gate: HumanGateProtocol | None = None,
        context_persistence: ContextPersistenceProtocol | None = None,
        log_dir: Path | None = None,
        auto_halt: bool = True,
    ) -> None:
        self.ksiega_path = Path(ksiega_path)
        self.human_gate = human_gate
        self.context_persistence = context_persistence
        self.log_dir = log_dir or Path("results/book_guardian")
        self.auto_halt = auto_halt

        self._baseline: KsiegaSnapshot | None = None
        self._check_count = 0
        self._drift_reports: list[DriftReport] = []

        # Compute baseline on init
        self._baseline = self._snapshot()
        if not self._baseline.exists:
            logger.warning(
                "BookGuardian: Księga file not found at %s — "
                "guardian initialized but baseline is empty",
                self.ksiega_path,
            )
        else:
            logger.info(
                "BookGuardian initialized — Księga=%s SHA=%s size=%d",
                self.ksiega_path, self._baseline.sha256[:16],
                self._baseline.size_bytes,
            )

        # Persist baseline
        self._write_baseline()

    # ------------------------------------------------------------------
    # SHA-256 hashing
    # ------------------------------------------------------------------

    @staticmethod
    def _sha256_file(path: Path) -> str:
        """Compute SHA-256 of a file in 64KB chunks."""
        h = hashlib.sha256()
        with open(path, "rb") as f:
            while True:
                chunk = f.read(_HASH_BUF_SIZE)
                if not chunk:
                    break
                h.update(chunk)
        return h.hexdigest()

    # ------------------------------------------------------------------
    # Snapshot
    # ------------------------------------------------------------------

    def _snapshot(self) -> KsiegaSnapshot:
        """Take a snapshot of the Księga file.

        PIPELINE-011 v6.2.0 memoize: when file metadata (mtime, size) is
        unchanged since the last snapshot we skip the expensive SHA-256
        recomputation and return the cached hash. This turns BookGuardian
        from O(file_size) per check into O(1) when the file hasn't moved,
        which matters because orchestrator calls check() after every agent
        tick. Opt-out via env ``SYLION_BOOKGUARDIAN_NO_MEMOIZE=1``.
        """
        p = self.ksiega_path
        if not p.exists() or not p.is_file():
            # Invalidate memoized hash on disappearance
            self.__dict__["_memo_sha_key"] = None
            return KsiegaSnapshot(
                file_path=str(p), sha256="",
                size_bytes=0, mtime=0.0, exists=False,
            )
        stat = p.stat()
        memo_key = (str(p), stat.st_mtime_ns, stat.st_size)
        import os as _os
        if _os.getenv("SYLION_BOOKGUARDIAN_NO_MEMOIZE", "0") != "1":
            cached_key = self.__dict__.get("_memo_sha_key")
            if cached_key == memo_key:
                cached_sha = self.__dict__.get("_memo_sha_value", "")
                if cached_sha:
                    return KsiegaSnapshot(
                        file_path=str(p),
                        sha256=cached_sha,
                        size_bytes=stat.st_size,
                        mtime=stat.st_mtime,
                        exists=True,
                    )
        # Cache miss: compute + store
        sha = self._sha256_file(p)
        self.__dict__["_memo_sha_key"] = memo_key
        self.__dict__["_memo_sha_value"] = sha
        return KsiegaSnapshot(
            file_path=str(p),
            sha256=sha,
            size_bytes=stat.st_size,
            mtime=stat.st_mtime,
            exists=True,
        )

    # ------------------------------------------------------------------
    # Check — main entry point
    # ------------------------------------------------------------------

    def check(self) -> bool:
        """Check Księga integrity against baseline.

        Returns True if OK, False if drift detected.
        On drift: logs, writes report, optionally escalates to Human Gate.

        NOTE (v5.9.1): The ``auto_halt`` constructor parameter is stored as
        ``self.auto_halt`` but is NOT acted upon internally by this method.
        The responsibility for halting the pipeline on drift is intentionally
        delegated to the **caller** — BookGuardian only detects and escalates.
        Callers MUST check the return value and halt explicitly, e.g.::

            if not guardian.check():
                sys.exit(1)  # or raise, or trigger HumanGate

        Omitting this check means drift will be logged/escalated but the
        pipeline will continue running. See ``book_guardian_example.py`` for
        the recommended orchestrator integration pattern.
        """
        self._check_count += 1
        current = self._snapshot()

        # Case 1: baseline was empty (Księga didn't exist at init)
        if self._baseline is None or not self._baseline.exists:
            if current.exists:
                # Księga appeared — suspicious but not necessarily drift
                logger.warning(
                    "BookGuardian: Księga appeared after init — "
                    "recalculating baseline (SHA=%s)",
                    current.sha256[:16],
                )
                self._baseline = current
                self._write_baseline()
                return True
            return True  # Still missing — nothing to check

        # Case 2: file disappeared
        if not current.exists:
            report = DriftReport(
                baseline=self._baseline, current=current,
                drift_detected=True,
                description=(
                    f"CRITICAL: Księga file DELETED! "
                    f"Was: {self._baseline.file_path} "
                    f"(SHA={self._baseline.sha256[:16]}, "
                    f"size={self._baseline.size_bytes})"
                ),
            )
            self._on_drift(report)
            return False

        # Case 3: SHA mismatch
        if self._baseline.sha256 != current.sha256:
            report = DriftReport(
                baseline=self._baseline, current=current,
                drift_detected=True,
                description=(
                    f"CRITICAL: Księga SHA-256 CHANGED! "
                    f"Baseline: {self._baseline.sha256[:16]} → "
                    f"Current: {current.sha256[:16]}. "
                    f"Size: {self._baseline.size_bytes} → {current.size_bytes}. "
                    f"Someone or something modified the normative document!"
                ),
            )
            self._on_drift(report)
            return False

        # OK
        logger.debug(
            "BookGuardian check #%d OK — SHA=%s",
            self._check_count, current.sha256[:16],
        )
        return True

    # ------------------------------------------------------------------
    # Drift handler
    # ------------------------------------------------------------------

    def _on_drift(self, report: DriftReport) -> None:
        """Handle detected Księga drift."""
        self._drift_reports.append(report)

        logger.critical(
            "KSIĘGA DRIFT DETECTED — %s", report.description,
        )

        # Write drift report to disk
        self._write_drift_report(report)

        # Record in ContextPersistence
        if self.context_persistence:
            try:
                from loop_guard import EventType
                self.context_persistence.record_event(
                    event_type=EventType.ESCALATED,
                    agent_id=self.AGENT_ID,
                    description=report.description,
                    details=report.to_dict(),
                )
            except ImportError:
                pass

        # Escalate to Human Gate (CRITICAL)
        if self.human_gate:
            self._escalate_to_human_gate(report)

    def _escalate_to_human_gate(self, report: DriftReport) -> None:
        """Escalate Księga drift to Human Gate at CRITICAL level."""
        try:
            from supervisor import GateRequest, GateLevel
        except ImportError:
            logger.error("Cannot escalate — supervisor module not available.")
            return

        gate_request = GateRequest(
            id=f"book-drift-{self._check_count}",
            agent_name=self.AGENT_ID,
            stage="BOOK_GUARDIAN",
            level=GateLevel.CRITICAL,
            title="KRYTYCZNY: DRYF KSIĘGI WYKRYTY",
            description=(
                f"BookGuardian wykrył zmianę Księgi SYLION!\n\n"
                f"Plik: {report.baseline.file_path}\n"
                f"SHA baseline: {report.baseline.sha256}\n"
                f"SHA aktualny: {report.current.sha256}\n"
                f"Rozmiar baseline: {report.baseline.size_bytes} B\n"
                f"Rozmiar aktualny: {report.current.size_bytes} B\n\n"
                f"Opis: {report.description}\n\n"
                f"PIPELINE MUSI ZOSTAĆ ZATRZYMANY dopóki dryf nie zostanie "
                f"zbadany i rozwiązany przez administratora."
            ),
            action_plan=[
                {"step": "1. Zbadaj kto/co zmodyfikował Księgę"},
                {"step": "2. Jeśli zmiana autoryzowana: zaktualizuj baseline SHA"},
                {"step": "3. Jeśli zmiana nieautoryzowana: przywróć oryginał"},
                {"step": "4. Dopiero po rozwiązaniu: kontynuuj pipeline"},
            ],
            risk_assessment=(
                "Księga jest normatywnym dokumentem pipeline'u. Jej modyfikacja "
                "bez autoryzacji oznacza, że wszystkie wymagania mogły się zmienić, "
                "co unieważnia audyty i patche oparte na poprzednim baseline."
            ),
            proposed_commands=[],
            metadata={
                "drift_report": report.to_dict(),
                "check_number": self._check_count,
            },
        )

        try:
            self.human_gate.request_approval(gate_request)
        except Exception as e:
            logger.error("Failed to escalate Księga drift to Human Gate: %s", e)

    # ------------------------------------------------------------------
    # Manual baseline update (after authorized change)
    # ------------------------------------------------------------------

    def update_baseline(self, authorized_by: str = "") -> KsiegaSnapshot:
        """Manually update the baseline SHA after an authorized Księga change.

        This requires explicit human authorization and is logged.
        """
        old = self._baseline
        self._baseline = self._snapshot()

        logger.warning(
            "BookGuardian: BASELINE UPDATED by '%s' — "
            "old SHA=%s → new SHA=%s",
            authorized_by or "unknown",
            old.sha256[:16] if old else "N/A",
            self._baseline.sha256[:16],
        )

        self._write_baseline()
        self._write_audit_entry("baseline_update", {
            "authorized_by": authorized_by,
            "old_sha": old.sha256 if old else None,
            "new_sha": self._baseline.sha256,
        })

        return self._baseline

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def baseline(self) -> KsiegaSnapshot | None:
        return self._baseline

    @property
    def baseline_sha(self) -> str:
        return self._baseline.sha256 if self._baseline else ""

    @property
    def check_count(self) -> int:
        return self._check_count

    @property
    def drift_count(self) -> int:
        return len(self._drift_reports)

    @property
    def is_healthy(self) -> bool:
        return len(self._drift_reports) == 0

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _write_baseline(self) -> None:
        """Write baseline snapshot to disk."""
        try:
            self.log_dir.mkdir(parents=True, exist_ok=True)
            path = self.log_dir / "baseline.json"
            with open(path, "w", encoding="utf-8") as f:
                json.dump(
                    self._baseline.to_dict() if self._baseline else {},
                    f, ensure_ascii=False, indent=2,
                )
        except OSError as e:
            logger.error("Failed to write baseline: %s", e)

    def _write_drift_report(self, report: DriftReport) -> None:
        """Append drift report to JSONL log."""
        try:
            self.log_dir.mkdir(parents=True, exist_ok=True)
            path = self.log_dir / "drift_log.jsonl"
            with open(path, "a", encoding="utf-8") as f:
                f.write(json.dumps(report.to_dict(), ensure_ascii=False) + "\n")
        except OSError as e:
            logger.error("Failed to write drift report: %s", e)

    def _write_audit_entry(self, action: str, details: dict) -> None:
        """Append audit entry to JSONL log."""
        try:
            self.log_dir.mkdir(parents=True, exist_ok=True)
            path = self.log_dir / "audit_log.jsonl"
            entry = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "agent_id": self.AGENT_ID,
                "action": action,
                "details": details,
            }
            with open(path, "a", encoding="utf-8") as f:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        except OSError as e:
            logger.error("Failed to write audit entry: %s", e)

    def load_baseline(self, path: Path) -> None:
        """Load a previously stored baseline from JSON."""
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if data:
                self._baseline = KsiegaSnapshot.from_dict(data)
                logger.info(
                    "BookGuardian: loaded baseline from %s — SHA=%s",
                    path, self._baseline.sha256[:16],
                )
        except (OSError, json.JSONDecodeError, KeyError) as e:
            logger.error("Failed to load baseline from %s: %s", path, e)

    # ------------------------------------------------------------------
    # Report
    # ------------------------------------------------------------------

    def export_report(self) -> dict[str, Any]:
        """Export full BookGuardian state as dict."""
        return {
            "agent_id": self.AGENT_ID,
            "ksiega_path": str(self.ksiega_path),
            "baseline": self._baseline.to_dict() if self._baseline else None,
            "check_count": self._check_count,
            "drift_count": self.drift_count,
            "is_healthy": self.is_healthy,
            "drift_reports": [r.to_dict() for r in self._drift_reports],
        }


# ---------------------------------------------------------------------------
# Standalone watchdog mode
# ---------------------------------------------------------------------------

def run_watchdog(
    ksiega_path: Path,
    interval_sec: int = 3600,
    log_dir: Path = Path("results/book_guardian"),
) -> None:
    """Run BookGuardian as standalone cron-like watchdog.

    Checks Księga SHA every `interval_sec` seconds.
    Logs to results/book_guardian/.
    """
    guardian = BookGuardian(
        ksiega_path=ksiega_path,
        log_dir=log_dir,
    )

    print(f"BookGuardian watchdog started — checking every {interval_sec}s")
    print(f"Księga: {ksiega_path}")
    print(f"Baseline SHA: {guardian.baseline_sha[:16]}...")

    try:
        while True:
            time.sleep(interval_sec)
            ok = guardian.check()
            status = "OK" if ok else "DRIFT DETECTED"
            print(
                f"[{datetime.now(timezone.utc).isoformat()}] "
                f"BookGuardian check #{guardian.check_count}: {status}"
            )
            if not ok:
                print("  ⚠️ CRITICAL: Księga drift detected! Check drift_log.jsonl")
    except KeyboardInterrupt:
        print("\nBookGuardian watchdog stopped.")


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def _run_tests() -> None:
    """Basic self-tests for BookGuardian."""
    import tempfile
    import unittest

    class TestBookGuardian(unittest.TestCase):

        def setUp(self):
            self.tmpdir = tempfile.mkdtemp()
            self.ksiega = Path(self.tmpdir) / "ksiega.docx"
            self.ksiega.write_bytes(b"Ksiega SYLION 3.4 FIXED content here")
            self.log_dir = Path(self.tmpdir) / "logs"

        def tearDown(self):
            import shutil
            shutil.rmtree(self.tmpdir, ignore_errors=True)

        def test_01_init_computes_baseline(self):
            g = BookGuardian(self.ksiega, log_dir=self.log_dir)
            self.assertIsNotNone(g.baseline)
            self.assertTrue(g.baseline.exists)
            self.assertTrue(len(g.baseline_sha) == 64)
            print(f"  ✓ test_01: baseline SHA={g.baseline_sha[:16]}")

        def test_02_check_ok_unchanged(self):
            g = BookGuardian(self.ksiega, log_dir=self.log_dir)
            self.assertTrue(g.check())
            self.assertTrue(g.is_healthy)
            self.assertEqual(g.drift_count, 0)
            print("  ✓ test_02: check OK when unchanged")

        def test_03_detect_modification(self):
            g = BookGuardian(self.ksiega, log_dir=self.log_dir)
            # Modify Księga
            self.ksiega.write_bytes(b"MODIFIED CONTENT -- drift!")
            self.assertFalse(g.check())
            self.assertFalse(g.is_healthy)
            self.assertEqual(g.drift_count, 1)
            print("  ✓ test_03: drift detected on modification")

        def test_04_detect_deletion(self):
            g = BookGuardian(self.ksiega, log_dir=self.log_dir)
            self.ksiega.unlink()
            self.assertFalse(g.check())
            self.assertFalse(g.is_healthy)
            print("  ✓ test_04: drift detected on deletion")

        def test_05_update_baseline(self):
            g = BookGuardian(self.ksiega, log_dir=self.log_dir)
            old_sha = g.baseline_sha
            self.ksiega.write_bytes(b"Authorized new content")
            new_snap = g.update_baseline(authorized_by="admin")
            self.assertNotEqual(old_sha, new_snap.sha256)
            self.assertTrue(g.check())  # Now OK with new baseline
            print("  ✓ test_05: baseline update works")

        def test_06_missing_file_at_init(self):
            missing = Path(self.tmpdir) / "nonexistent.docx"
            g = BookGuardian(missing, log_dir=self.log_dir)
            self.assertFalse(g.baseline.exists)
            self.assertTrue(g.check())  # No file = nothing to check
            print("  ✓ test_06: graceful handling of missing file")

        def test_07_persistence(self):
            g = BookGuardian(self.ksiega, log_dir=self.log_dir)
            # Check baseline file was written
            baseline_file = self.log_dir / "baseline.json"
            self.assertTrue(baseline_file.exists())
            with open(baseline_file) as f:
                data = json.load(f)
            self.assertEqual(data["sha256"], g.baseline_sha)
            print("  ✓ test_07: baseline persisted to disk")

        def test_08_export_report(self):
            g = BookGuardian(self.ksiega, log_dir=self.log_dir)
            g.check()
            report = g.export_report()
            self.assertEqual(report["agent_id"], "book_guardian")
            self.assertTrue(report["is_healthy"])
            self.assertEqual(report["check_count"], 1)
            print("  ✓ test_08: export_report works")

        def test_09_human_gate_escalation(self):
            """Test that drift triggers Human Gate (mock)."""
            escalated = []

            class MockGate:
                def request_approval(self, req):
                    escalated.append(req)
                    return req

            g = BookGuardian(
                self.ksiega, human_gate=MockGate(), log_dir=self.log_dir,
            )
            self.ksiega.write_bytes(b"UNAUTHORIZED CHANGE")
            g.check()
            self.assertEqual(len(escalated), 1)
            # Check it's CRITICAL level
            from supervisor import GateLevel
            self.assertEqual(escalated[0].level, GateLevel.CRITICAL)
            print("  ✓ test_09: Human Gate CRITICAL escalation on drift")

    print("=" * 60)
    print("BookGuardian — self-tests")
    print("=" * 60)
    unittest.main(module=__name__, argv=[""], exit=False, verbosity=0)
    print("=" * 60)


if __name__ == "__main__":
    import sys
    if "--watchdog" in sys.argv:
        path = sys.argv[sys.argv.index("--watchdog") + 1] if len(sys.argv) > sys.argv.index("--watchdog") + 1 else "docs/Ksiega_SYLION_3_4_FIXED.docx"
        run_watchdog(Path(path))
    else:
        _run_tests()
