# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sylion_common_pb2 as sylion__common__pb2
import sylion_core_pb2 as sylion__core__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sylion_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModuleRegistryServiceStub(object):
    """* Module registry – tracks every AEIS module and its lifecycle. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModule = channel.unary_unary(
                '/sylion.ModuleRegistryService/RegisterModule',
                request_serializer=sylion__core__pb2.RegisterModuleRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.RegisterModuleResponse.FromString,
                _registered_method=True)
        self.GetModule = channel.unary_unary(
                '/sylion.ModuleRegistryService/GetModule',
                request_serializer=sylion__core__pb2.GetModuleRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.GetModuleResponse.FromString,
                _registered_method=True)
        self.ListModules = channel.unary_unary(
                '/sylion.ModuleRegistryService/ListModules',
                request_serializer=sylion__core__pb2.ListModulesRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.ListModulesResponse.FromString,
                _registered_method=True)
        self.TransitionModule = channel.unary_unary(
                '/sylion.ModuleRegistryService/TransitionModule',
                request_serializer=sylion__core__pb2.TransitionModuleRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.TransitionModuleResponse.FromString,
                _registered_method=True)


class ModuleRegistryServiceServicer(object):
    """* Module registry – tracks every AEIS module and its lifecycle. 
    """

    def RegisterModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransitionModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModule': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModule,
                    request_deserializer=sylion__core__pb2.RegisterModuleRequest.FromString,
                    response_serializer=sylion__core__pb2.RegisterModuleResponse.SerializeToString,
            ),
            'GetModule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModule,
                    request_deserializer=sylion__core__pb2.GetModuleRequest.FromString,
                    response_serializer=sylion__core__pb2.GetModuleResponse.SerializeToString,
            ),
            'ListModules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModules,
                    request_deserializer=sylion__core__pb2.ListModulesRequest.FromString,
                    response_serializer=sylion__core__pb2.ListModulesResponse.SerializeToString,
            ),
            'TransitionModule': grpc.unary_unary_rpc_method_handler(
                    servicer.TransitionModule,
                    request_deserializer=sylion__core__pb2.TransitionModuleRequest.FromString,
                    response_serializer=sylion__core__pb2.TransitionModuleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.ModuleRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.ModuleRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleRegistryService(object):
    """* Module registry – tracks every AEIS module and its lifecycle. 
    """

    @staticmethod
    def RegisterModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModuleRegistryService/RegisterModule',
            sylion__core__pb2.RegisterModuleRequest.SerializeToString,
            sylion__core__pb2.RegisterModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModuleRegistryService/GetModule',
            sylion__core__pb2.GetModuleRequest.SerializeToString,
            sylion__core__pb2.GetModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModuleRegistryService/ListModules',
            sylion__core__pb2.ListModulesRequest.SerializeToString,
            sylion__core__pb2.ListModulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransitionModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModuleRegistryService/TransitionModule',
            sylion__core__pb2.TransitionModuleRequest.SerializeToString,
            sylion__core__pb2.TransitionModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventBusServiceStub(object):
    """* Central event bus – pub/sub with replay and acknowledgement. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishEvent = channel.unary_unary(
                '/sylion.EventBusService/PublishEvent',
                request_serializer=sylion__core__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.PublishEventResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/sylion.EventBusService/Subscribe',
                request_serializer=sylion__core__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.Event.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/sylion.EventBusService/ListEvents',
                request_serializer=sylion__core__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.AckEvent = channel.unary_unary(
                '/sylion.EventBusService/AckEvent',
                request_serializer=sylion__core__pb2.AckEventRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.AckEventResponse.FromString,
                _registered_method=True)


class EventBusServiceServicer(object):
    """* Central event bus – pub/sub with replay and acknowledgement. 
    """

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventBusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=sylion__core__pb2.PublishEventRequest.FromString,
                    response_serializer=sylion__core__pb2.PublishEventResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=sylion__core__pb2.SubscribeRequest.FromString,
                    response_serializer=sylion__core__pb2.Event.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=sylion__core__pb2.ListEventsRequest.FromString,
                    response_serializer=sylion__core__pb2.ListEventsResponse.SerializeToString,
            ),
            'AckEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AckEvent,
                    request_deserializer=sylion__core__pb2.AckEventRequest.FromString,
                    response_serializer=sylion__core__pb2.AckEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.EventBusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.EventBusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventBusService(object):
    """* Central event bus – pub/sub with replay and acknowledgement. 
    """

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.EventBusService/PublishEvent',
            sylion__core__pb2.PublishEventRequest.SerializeToString,
            sylion__core__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sylion.EventBusService/Subscribe',
            sylion__core__pb2.SubscribeRequest.SerializeToString,
            sylion__core__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.EventBusService/ListEvents',
            sylion__core__pb2.ListEventsRequest.SerializeToString,
            sylion__core__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.EventBusService/AckEvent',
            sylion__core__pb2.AckEventRequest.SerializeToString,
            sylion__core__pb2.AckEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EvidenceSpineServiceStub(object):
    """* Cryptographic evidence spine – append-only, verifiable chain. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEntry = channel.unary_unary(
                '/sylion.EvidenceSpineService/AppendEntry',
                request_serializer=sylion__core__pb2.AppendEntryRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.AppendEntryResponse.FromString,
                _registered_method=True)
        self.VerifyChain = channel.unary_unary(
                '/sylion.EvidenceSpineService/VerifyChain',
                request_serializer=sylion__core__pb2.VerifyChainRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.VerifyChainResponse.FromString,
                _registered_method=True)
        self.Replay = channel.unary_stream(
                '/sylion.EvidenceSpineService/Replay',
                request_serializer=sylion__core__pb2.ReplayRequest.SerializeToString,
                response_deserializer=sylion__common__pb2.EvidenceEntry.FromString,
                _registered_method=True)
        self.GetEntry = channel.unary_unary(
                '/sylion.EvidenceSpineService/GetEntry',
                request_serializer=sylion__core__pb2.GetEntryRequest.SerializeToString,
                response_deserializer=sylion__core__pb2.GetEntryResponse.FromString,
                _registered_method=True)


class EvidenceSpineServiceServicer(object):
    """* Cryptographic evidence spine – append-only, verifiable chain. 
    """

    def AppendEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvidenceSpineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntry,
                    request_deserializer=sylion__core__pb2.AppendEntryRequest.FromString,
                    response_serializer=sylion__core__pb2.AppendEntryResponse.SerializeToString,
            ),
            'VerifyChain': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyChain,
                    request_deserializer=sylion__core__pb2.VerifyChainRequest.FromString,
                    response_serializer=sylion__core__pb2.VerifyChainResponse.SerializeToString,
            ),
            'Replay': grpc.unary_stream_rpc_method_handler(
                    servicer.Replay,
                    request_deserializer=sylion__core__pb2.ReplayRequest.FromString,
                    response_serializer=sylion__common__pb2.EvidenceEntry.SerializeToString,
            ),
            'GetEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntry,
                    request_deserializer=sylion__core__pb2.GetEntryRequest.FromString,
                    response_serializer=sylion__core__pb2.GetEntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.EvidenceSpineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.EvidenceSpineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EvidenceSpineService(object):
    """* Cryptographic evidence spine – append-only, verifiable chain. 
    """

    @staticmethod
    def AppendEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.EvidenceSpineService/AppendEntry',
            sylion__core__pb2.AppendEntryRequest.SerializeToString,
            sylion__core__pb2.AppendEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.EvidenceSpineService/VerifyChain',
            sylion__core__pb2.VerifyChainRequest.SerializeToString,
            sylion__core__pb2.VerifyChainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sylion.EvidenceSpineService/Replay',
            sylion__core__pb2.ReplayRequest.SerializeToString,
            sylion__common__pb2.EvidenceEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.EvidenceSpineService/GetEntry',
            sylion__core__pb2.GetEntryRequest.SerializeToString,
            sylion__core__pb2.GetEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
