# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sylion_execution_pb2 as sylion__execution__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sylion_execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub(object):
    """* Workflow service – DAG-based workflow definitions and execution. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWorkflow = channel.unary_unary(
                '/sylion.WorkflowService/CreateWorkflow',
                request_serializer=sylion__execution__pb2.CreateWorkflowRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.CreateWorkflowResponse.FromString,
                _registered_method=True)
        self.RunWorkflow = channel.unary_unary(
                '/sylion.WorkflowService/RunWorkflow',
                request_serializer=sylion__execution__pb2.RunWorkflowRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.RunWorkflowResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/sylion.WorkflowService/GetRun',
                request_serializer=sylion__execution__pb2.GetRunRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.GetRunResponse.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_unary(
                '/sylion.WorkflowService/ListWorkflows',
                request_serializer=sylion__execution__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.ListWorkflowsResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer(object):
    """* Workflow service – DAG-based workflow definitions and execution. 
    """

    def CreateWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkflow,
                    request_deserializer=sylion__execution__pb2.CreateWorkflowRequest.FromString,
                    response_serializer=sylion__execution__pb2.CreateWorkflowResponse.SerializeToString,
            ),
            'RunWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RunWorkflow,
                    request_deserializer=sylion__execution__pb2.RunWorkflowRequest.FromString,
                    response_serializer=sylion__execution__pb2.RunWorkflowResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=sylion__execution__pb2.GetRunRequest.FromString,
                    response_serializer=sylion__execution__pb2.GetRunResponse.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=sylion__execution__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=sylion__execution__pb2.ListWorkflowsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService(object):
    """* Workflow service – DAG-based workflow definitions and execution. 
    """

    @staticmethod
    def CreateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.WorkflowService/CreateWorkflow',
            sylion__execution__pb2.CreateWorkflowRequest.SerializeToString,
            sylion__execution__pb2.CreateWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.WorkflowService/RunWorkflow',
            sylion__execution__pb2.RunWorkflowRequest.SerializeToString,
            sylion__execution__pb2.RunWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.WorkflowService/GetRun',
            sylion__execution__pb2.GetRunRequest.SerializeToString,
            sylion__execution__pb2.GetRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.WorkflowService/ListWorkflows',
            sylion__execution__pb2.ListWorkflowsRequest.SerializeToString,
            sylion__execution__pb2.ListWorkflowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class JobServiceStub(object):
    """* Job service – background job queue with scheduling and stats. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/sylion.JobService/SubmitJob',
                request_serializer=sylion__execution__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.SubmitJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/sylion.JobService/GetJob',
                request_serializer=sylion__execution__pb2.GetJobRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.GetNextJob = channel.unary_unary(
                '/sylion.JobService/GetNextJob',
                request_serializer=sylion__execution__pb2.GetNextJobRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.GetNextJobResponse.FromString,
                _registered_method=True)
        self.CompleteJob = channel.unary_unary(
                '/sylion.JobService/CompleteJob',
                request_serializer=sylion__execution__pb2.CompleteJobRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.CompleteJobResponse.FromString,
                _registered_method=True)
        self.FailJob = channel.unary_unary(
                '/sylion.JobService/FailJob',
                request_serializer=sylion__execution__pb2.FailJobRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.FailJobResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/sylion.JobService/GetStats',
                request_serializer=sylion__execution__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=sylion__execution__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class JobServiceServicer(object):
    """* Job service – background job queue with scheduling and stats. 
    """

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=sylion__execution__pb2.SubmitJobRequest.FromString,
                    response_serializer=sylion__execution__pb2.SubmitJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=sylion__execution__pb2.GetJobRequest.FromString,
                    response_serializer=sylion__execution__pb2.GetJobResponse.SerializeToString,
            ),
            'GetNextJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextJob,
                    request_deserializer=sylion__execution__pb2.GetNextJobRequest.FromString,
                    response_serializer=sylion__execution__pb2.GetNextJobResponse.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=sylion__execution__pb2.CompleteJobRequest.FromString,
                    response_serializer=sylion__execution__pb2.CompleteJobResponse.SerializeToString,
            ),
            'FailJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FailJob,
                    request_deserializer=sylion__execution__pb2.FailJobRequest.FromString,
                    response_serializer=sylion__execution__pb2.FailJobResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=sylion__execution__pb2.GetStatsRequest.FromString,
                    response_serializer=sylion__execution__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """* Job service – background job queue with scheduling and stats. 
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.JobService/SubmitJob',
            sylion__execution__pb2.SubmitJobRequest.SerializeToString,
            sylion__execution__pb2.SubmitJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.JobService/GetJob',
            sylion__execution__pb2.GetJobRequest.SerializeToString,
            sylion__execution__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.JobService/GetNextJob',
            sylion__execution__pb2.GetNextJobRequest.SerializeToString,
            sylion__execution__pb2.GetNextJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.JobService/CompleteJob',
            sylion__execution__pb2.CompleteJobRequest.SerializeToString,
            sylion__execution__pb2.CompleteJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.JobService/FailJob',
            sylion__execution__pb2.FailJobRequest.SerializeToString,
            sylion__execution__pb2.FailJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.JobService/GetStats',
            sylion__execution__pb2.GetStatsRequest.SerializeToString,
            sylion__execution__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
