# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sylion_governance_pb2 as sylion__governance__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sylion_governance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GovernanceServiceStub(object):
    """* Governance service – decision classification and proposal lifecycle. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyDecision = channel.unary_unary(
                '/sylion.GovernanceService/ClassifyDecision',
                request_serializer=sylion__governance__pb2.ClassifyDecisionRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.ClassifyDecisionResponse.FromString,
                _registered_method=True)
        self.CreateProposal = channel.unary_unary(
                '/sylion.GovernanceService/CreateProposal',
                request_serializer=sylion__governance__pb2.CreateProposalRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.CreateProposalResponse.FromString,
                _registered_method=True)
        self.GetProposal = channel.unary_unary(
                '/sylion.GovernanceService/GetProposal',
                request_serializer=sylion__governance__pb2.GetProposalRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.GetProposalResponse.FromString,
                _registered_method=True)
        self.ListProposals = channel.unary_unary(
                '/sylion.GovernanceService/ListProposals',
                request_serializer=sylion__governance__pb2.ListProposalsRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.ListProposalsResponse.FromString,
                _registered_method=True)
        self.ApproveProposal = channel.unary_unary(
                '/sylion.GovernanceService/ApproveProposal',
                request_serializer=sylion__governance__pb2.ProposalActionRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.ProposalActionResponse.FromString,
                _registered_method=True)
        self.RejectProposal = channel.unary_unary(
                '/sylion.GovernanceService/RejectProposal',
                request_serializer=sylion__governance__pb2.ProposalActionRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.ProposalActionResponse.FromString,
                _registered_method=True)


class GovernanceServiceServicer(object):
    """* Governance service – decision classification and proposal lifecycle. 
    """

    def ClassifyDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProposals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GovernanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyDecision,
                    request_deserializer=sylion__governance__pb2.ClassifyDecisionRequest.FromString,
                    response_serializer=sylion__governance__pb2.ClassifyDecisionResponse.SerializeToString,
            ),
            'CreateProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProposal,
                    request_deserializer=sylion__governance__pb2.CreateProposalRequest.FromString,
                    response_serializer=sylion__governance__pb2.CreateProposalResponse.SerializeToString,
            ),
            'GetProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProposal,
                    request_deserializer=sylion__governance__pb2.GetProposalRequest.FromString,
                    response_serializer=sylion__governance__pb2.GetProposalResponse.SerializeToString,
            ),
            'ListProposals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProposals,
                    request_deserializer=sylion__governance__pb2.ListProposalsRequest.FromString,
                    response_serializer=sylion__governance__pb2.ListProposalsResponse.SerializeToString,
            ),
            'ApproveProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveProposal,
                    request_deserializer=sylion__governance__pb2.ProposalActionRequest.FromString,
                    response_serializer=sylion__governance__pb2.ProposalActionResponse.SerializeToString,
            ),
            'RejectProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectProposal,
                    request_deserializer=sylion__governance__pb2.ProposalActionRequest.FromString,
                    response_serializer=sylion__governance__pb2.ProposalActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.GovernanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.GovernanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GovernanceService(object):
    """* Governance service – decision classification and proposal lifecycle. 
    """

    @staticmethod
    def ClassifyDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.GovernanceService/ClassifyDecision',
            sylion__governance__pb2.ClassifyDecisionRequest.SerializeToString,
            sylion__governance__pb2.ClassifyDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.GovernanceService/CreateProposal',
            sylion__governance__pb2.CreateProposalRequest.SerializeToString,
            sylion__governance__pb2.CreateProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.GovernanceService/GetProposal',
            sylion__governance__pb2.GetProposalRequest.SerializeToString,
            sylion__governance__pb2.GetProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProposals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.GovernanceService/ListProposals',
            sylion__governance__pb2.ListProposalsRequest.SerializeToString,
            sylion__governance__pb2.ListProposalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.GovernanceService/ApproveProposal',
            sylion__governance__pb2.ProposalActionRequest.SerializeToString,
            sylion__governance__pb2.ProposalActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.GovernanceService/RejectProposal',
            sylion__governance__pb2.ProposalActionRequest.SerializeToString,
            sylion__governance__pb2.ProposalActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CouncilServiceStub(object):
    """* Council service – voting sessions and human-in-the-loop gates. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/sylion.CouncilService/CreateSession',
                request_serializer=sylion__governance__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.CastVote = channel.unary_unary(
                '/sylion.CouncilService/CastVote',
                request_serializer=sylion__governance__pb2.CastVoteRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.CastVoteResponse.FromString,
                _registered_method=True)
        self.TallyVotes = channel.unary_unary(
                '/sylion.CouncilService/TallyVotes',
                request_serializer=sylion__governance__pb2.TallyVotesRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.TallyVotesResponse.FromString,
                _registered_method=True)
        self.HumanGate = channel.unary_unary(
                '/sylion.CouncilService/HumanGate',
                request_serializer=sylion__governance__pb2.HumanGateRequest.SerializeToString,
                response_deserializer=sylion__governance__pb2.HumanGateResponse.FromString,
                _registered_method=True)


class CouncilServiceServicer(object):
    """* Council service – voting sessions and human-in-the-loop gates. 
    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CastVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TallyVotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HumanGate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CouncilServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=sylion__governance__pb2.CreateSessionRequest.FromString,
                    response_serializer=sylion__governance__pb2.CreateSessionResponse.SerializeToString,
            ),
            'CastVote': grpc.unary_unary_rpc_method_handler(
                    servicer.CastVote,
                    request_deserializer=sylion__governance__pb2.CastVoteRequest.FromString,
                    response_serializer=sylion__governance__pb2.CastVoteResponse.SerializeToString,
            ),
            'TallyVotes': grpc.unary_unary_rpc_method_handler(
                    servicer.TallyVotes,
                    request_deserializer=sylion__governance__pb2.TallyVotesRequest.FromString,
                    response_serializer=sylion__governance__pb2.TallyVotesResponse.SerializeToString,
            ),
            'HumanGate': grpc.unary_unary_rpc_method_handler(
                    servicer.HumanGate,
                    request_deserializer=sylion__governance__pb2.HumanGateRequest.FromString,
                    response_serializer=sylion__governance__pb2.HumanGateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.CouncilService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.CouncilService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CouncilService(object):
    """* Council service – voting sessions and human-in-the-loop gates. 
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.CouncilService/CreateSession',
            sylion__governance__pb2.CreateSessionRequest.SerializeToString,
            sylion__governance__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CastVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.CouncilService/CastVote',
            sylion__governance__pb2.CastVoteRequest.SerializeToString,
            sylion__governance__pb2.CastVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TallyVotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.CouncilService/TallyVotes',
            sylion__governance__pb2.TallyVotesRequest.SerializeToString,
            sylion__governance__pb2.TallyVotesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HumanGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.CouncilService/HumanGate',
            sylion__governance__pb2.HumanGateRequest.SerializeToString,
            sylion__governance__pb2.HumanGateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
