# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sylion_cognitive_pb2 as sylion__cognitive__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sylion_cognitive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelRouterServiceStub(object):
    """* Model router – registers LLM/SLM models and routes requests. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/sylion.ModelRouterService/RegisterModel',
                request_serializer=sylion__cognitive__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.RegisterModelResponse.FromString,
                _registered_method=True)
        self.RouteRequest = channel.unary_unary(
                '/sylion.ModelRouterService/RouteRequest',
                request_serializer=sylion__cognitive__pb2.RouteRequestRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.RouteRequestResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/sylion.ModelRouterService/ListModels',
                request_serializer=sylion__cognitive__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.GetUsageStats = channel.unary_unary(
                '/sylion.ModelRouterService/GetUsageStats',
                request_serializer=sylion__cognitive__pb2.GetUsageStatsRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.GetUsageStatsResponse.FromString,
                _registered_method=True)


class ModelRouterServiceServicer(object):
    """* Model router – registers LLM/SLM models and routes requests. 
    """

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelRouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=sylion__cognitive__pb2.RegisterModelRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.RegisterModelResponse.SerializeToString,
            ),
            'RouteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteRequest,
                    request_deserializer=sylion__cognitive__pb2.RouteRequestRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.RouteRequestResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=sylion__cognitive__pb2.ListModelsRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetUsageStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageStats,
                    request_deserializer=sylion__cognitive__pb2.GetUsageStatsRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.GetUsageStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.ModelRouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.ModelRouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelRouterService(object):
    """* Model router – registers LLM/SLM models and routes requests. 
    """

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModelRouterService/RegisterModel',
            sylion__cognitive__pb2.RegisterModelRequest.SerializeToString,
            sylion__cognitive__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModelRouterService/RouteRequest',
            sylion__cognitive__pb2.RouteRequestRequest.SerializeToString,
            sylion__cognitive__pb2.RouteRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModelRouterService/ListModels',
            sylion__cognitive__pb2.ListModelsRequest.SerializeToString,
            sylion__cognitive__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ModelRouterService/GetUsageStats',
            sylion__cognitive__pb2.GetUsageStatsRequest.SerializeToString,
            sylion__cognitive__pb2.GetUsageStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlanServiceStub(object):
    """* Plan service – hierarchical plan creation and task management. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePlan = channel.unary_unary(
                '/sylion.PlanService/CreatePlan',
                request_serializer=sylion__cognitive__pb2.CreatePlanRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.CreatePlanResponse.FromString,
                _registered_method=True)
        self.DecomposePlan = channel.unary_unary(
                '/sylion.PlanService/DecomposePlan',
                request_serializer=sylion__cognitive__pb2.DecomposePlanRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.DecomposePlanResponse.FromString,
                _registered_method=True)
        self.GetNextTask = channel.unary_unary(
                '/sylion.PlanService/GetNextTask',
                request_serializer=sylion__cognitive__pb2.GetNextTaskRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.GetNextTaskResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/sylion.PlanService/CompleteTask',
                request_serializer=sylion__cognitive__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=sylion__cognitive__pb2.CompleteTaskResponse.FromString,
                _registered_method=True)


class PlanServiceServicer(object):
    """* Plan service – hierarchical plan creation and task management. 
    """

    def CreatePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecomposePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlan,
                    request_deserializer=sylion__cognitive__pb2.CreatePlanRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.CreatePlanResponse.SerializeToString,
            ),
            'DecomposePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.DecomposePlan,
                    request_deserializer=sylion__cognitive__pb2.DecomposePlanRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.DecomposePlanResponse.SerializeToString,
            ),
            'GetNextTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextTask,
                    request_deserializer=sylion__cognitive__pb2.GetNextTaskRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.GetNextTaskResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=sylion__cognitive__pb2.CompleteTaskRequest.FromString,
                    response_serializer=sylion__cognitive__pb2.CompleteTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.PlanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.PlanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlanService(object):
    """* Plan service – hierarchical plan creation and task management. 
    """

    @staticmethod
    def CreatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.PlanService/CreatePlan',
            sylion__cognitive__pb2.CreatePlanRequest.SerializeToString,
            sylion__cognitive__pb2.CreatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecomposePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.PlanService/DecomposePlan',
            sylion__cognitive__pb2.DecomposePlanRequest.SerializeToString,
            sylion__cognitive__pb2.DecomposePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.PlanService/GetNextTask',
            sylion__cognitive__pb2.GetNextTaskRequest.SerializeToString,
            sylion__cognitive__pb2.GetNextTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.PlanService/CompleteTask',
            sylion__cognitive__pb2.CompleteTaskRequest.SerializeToString,
            sylion__cognitive__pb2.CompleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
