# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sylion_aeis_pb2 as sylion__aeis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sylion_aeis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AutonomyServiceStub(object):
    """* Autonomy service – tracks AEIS self-governance level and available actions. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/sylion.AutonomyService/GetStatus',
                request_serializer=sylion__aeis__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetStages = channel.unary_unary(
                '/sylion.AutonomyService/GetStages',
                request_serializer=sylion__aeis__pb2.GetStagesRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.GetStagesResponse.FromString,
                _registered_method=True)
        self.AdvanceStage = channel.unary_unary(
                '/sylion.AutonomyService/AdvanceStage',
                request_serializer=sylion__aeis__pb2.AdvanceStageRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.AdvanceStageResponse.FromString,
                _registered_method=True)
        self.GetActions = channel.unary_unary(
                '/sylion.AutonomyService/GetActions',
                request_serializer=sylion__aeis__pb2.GetActionsRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.GetActionsResponse.FromString,
                _registered_method=True)


class AutonomyServiceServicer(object):
    """* Autonomy service – tracks AEIS self-governance level and available actions. 
    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvanceStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutonomyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=sylion__aeis__pb2.GetStatusRequest.FromString,
                    response_serializer=sylion__aeis__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetStages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStages,
                    request_deserializer=sylion__aeis__pb2.GetStagesRequest.FromString,
                    response_serializer=sylion__aeis__pb2.GetStagesResponse.SerializeToString,
            ),
            'AdvanceStage': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvanceStage,
                    request_deserializer=sylion__aeis__pb2.AdvanceStageRequest.FromString,
                    response_serializer=sylion__aeis__pb2.AdvanceStageResponse.SerializeToString,
            ),
            'GetActions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActions,
                    request_deserializer=sylion__aeis__pb2.GetActionsRequest.FromString,
                    response_serializer=sylion__aeis__pb2.GetActionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.AutonomyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.AutonomyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutonomyService(object):
    """* Autonomy service – tracks AEIS self-governance level and available actions. 
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.AutonomyService/GetStatus',
            sylion__aeis__pb2.GetStatusRequest.SerializeToString,
            sylion__aeis__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.AutonomyService/GetStages',
            sylion__aeis__pb2.GetStagesRequest.SerializeToString,
            sylion__aeis__pb2.GetStagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvanceStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.AutonomyService/AdvanceStage',
            sylion__aeis__pb2.AdvanceStageRequest.SerializeToString,
            sylion__aeis__pb2.AdvanceStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.AutonomyService/GetActions',
            sylion__aeis__pb2.GetActionsRequest.SerializeToString,
            sylion__aeis__pb2.GetActionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExplanationServiceStub(object):
    """* Explanation service – generates and stores human-readable explanations. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateExplanation = channel.unary_unary(
                '/sylion.ExplanationService/CreateExplanation',
                request_serializer=sylion__aeis__pb2.CreateExplanationRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.CreateExplanationResponse.FromString,
                _registered_method=True)
        self.ListExplanations = channel.unary_unary(
                '/sylion.ExplanationService/ListExplanations',
                request_serializer=sylion__aeis__pb2.ListExplanationsRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.ListExplanationsResponse.FromString,
                _registered_method=True)
        self.GetExplanation = channel.unary_unary(
                '/sylion.ExplanationService/GetExplanation',
                request_serializer=sylion__aeis__pb2.GetExplanationRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.GetExplanationResponse.FromString,
                _registered_method=True)


class ExplanationServiceServicer(object):
    """* Explanation service – generates and stores human-readable explanations. 
    """

    def CreateExplanation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExplanations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExplanation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExplanationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateExplanation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExplanation,
                    request_deserializer=sylion__aeis__pb2.CreateExplanationRequest.FromString,
                    response_serializer=sylion__aeis__pb2.CreateExplanationResponse.SerializeToString,
            ),
            'ListExplanations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExplanations,
                    request_deserializer=sylion__aeis__pb2.ListExplanationsRequest.FromString,
                    response_serializer=sylion__aeis__pb2.ListExplanationsResponse.SerializeToString,
            ),
            'GetExplanation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExplanation,
                    request_deserializer=sylion__aeis__pb2.GetExplanationRequest.FromString,
                    response_serializer=sylion__aeis__pb2.GetExplanationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.ExplanationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.ExplanationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExplanationService(object):
    """* Explanation service – generates and stores human-readable explanations. 
    """

    @staticmethod
    def CreateExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ExplanationService/CreateExplanation',
            sylion__aeis__pb2.CreateExplanationRequest.SerializeToString,
            sylion__aeis__pb2.CreateExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExplanations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ExplanationService/ListExplanations',
            sylion__aeis__pb2.ListExplanationsRequest.SerializeToString,
            sylion__aeis__pb2.ListExplanationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ExplanationService/GetExplanation',
            sylion__aeis__pb2.GetExplanationRequest.SerializeToString,
            sylion__aeis__pb2.GetExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImprovementServiceStub(object):
    """* Improvement service – manages self-improvement proposals end-to-end. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateImprovement = channel.unary_unary(
                '/sylion.ImprovementService/CreateImprovement',
                request_serializer=sylion__aeis__pb2.CreateImprovementRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.CreateImprovementResponse.FromString,
                _registered_method=True)
        self.ListImprovements = channel.unary_unary(
                '/sylion.ImprovementService/ListImprovements',
                request_serializer=sylion__aeis__pb2.ListImprovementsRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.ListImprovementsResponse.FromString,
                _registered_method=True)
        self.GetNext = channel.unary_unary(
                '/sylion.ImprovementService/GetNext',
                request_serializer=sylion__aeis__pb2.GetNextRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.GetNextResponse.FromString,
                _registered_method=True)
        self.StartImprovement = channel.unary_unary(
                '/sylion.ImprovementService/StartImprovement',
                request_serializer=sylion__aeis__pb2.StartImprovementRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.StartImprovementResponse.FromString,
                _registered_method=True)
        self.CompleteImprovement = channel.unary_unary(
                '/sylion.ImprovementService/CompleteImprovement',
                request_serializer=sylion__aeis__pb2.CompleteImprovementRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.CompleteImprovementResponse.FromString,
                _registered_method=True)
        self.RejectImprovement = channel.unary_unary(
                '/sylion.ImprovementService/RejectImprovement',
                request_serializer=sylion__aeis__pb2.RejectImprovementRequest.SerializeToString,
                response_deserializer=sylion__aeis__pb2.RejectImprovementResponse.FromString,
                _registered_method=True)


class ImprovementServiceServicer(object):
    """* Improvement service – manages self-improvement proposals end-to-end. 
    """

    def CreateImprovement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListImprovements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartImprovement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteImprovement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectImprovement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImprovementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateImprovement': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateImprovement,
                    request_deserializer=sylion__aeis__pb2.CreateImprovementRequest.FromString,
                    response_serializer=sylion__aeis__pb2.CreateImprovementResponse.SerializeToString,
            ),
            'ListImprovements': grpc.unary_unary_rpc_method_handler(
                    servicer.ListImprovements,
                    request_deserializer=sylion__aeis__pb2.ListImprovementsRequest.FromString,
                    response_serializer=sylion__aeis__pb2.ListImprovementsResponse.SerializeToString,
            ),
            'GetNext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNext,
                    request_deserializer=sylion__aeis__pb2.GetNextRequest.FromString,
                    response_serializer=sylion__aeis__pb2.GetNextResponse.SerializeToString,
            ),
            'StartImprovement': grpc.unary_unary_rpc_method_handler(
                    servicer.StartImprovement,
                    request_deserializer=sylion__aeis__pb2.StartImprovementRequest.FromString,
                    response_serializer=sylion__aeis__pb2.StartImprovementResponse.SerializeToString,
            ),
            'CompleteImprovement': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteImprovement,
                    request_deserializer=sylion__aeis__pb2.CompleteImprovementRequest.FromString,
                    response_serializer=sylion__aeis__pb2.CompleteImprovementResponse.SerializeToString,
            ),
            'RejectImprovement': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectImprovement,
                    request_deserializer=sylion__aeis__pb2.RejectImprovementRequest.FromString,
                    response_serializer=sylion__aeis__pb2.RejectImprovementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.ImprovementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.ImprovementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImprovementService(object):
    """* Improvement service – manages self-improvement proposals end-to-end. 
    """

    @staticmethod
    def CreateImprovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ImprovementService/CreateImprovement',
            sylion__aeis__pb2.CreateImprovementRequest.SerializeToString,
            sylion__aeis__pb2.CreateImprovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListImprovements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ImprovementService/ListImprovements',
            sylion__aeis__pb2.ListImprovementsRequest.SerializeToString,
            sylion__aeis__pb2.ListImprovementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ImprovementService/GetNext',
            sylion__aeis__pb2.GetNextRequest.SerializeToString,
            sylion__aeis__pb2.GetNextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartImprovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ImprovementService/StartImprovement',
            sylion__aeis__pb2.StartImprovementRequest.SerializeToString,
            sylion__aeis__pb2.StartImprovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteImprovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ImprovementService/CompleteImprovement',
            sylion__aeis__pb2.CompleteImprovementRequest.SerializeToString,
            sylion__aeis__pb2.CompleteImprovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectImprovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.ImprovementService/RejectImprovement',
            sylion__aeis__pb2.RejectImprovementRequest.SerializeToString,
            sylion__aeis__pb2.RejectImprovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
