#!/usr/bin/env bash
# SYLION Pipeline v6.2.0 installer (Linux/Mac)
# Idempotentny — można uruchomić wielokrotnie bez efektów ubocznych.

set -euo pipefail

VERSION="6.2.0"
INSTALL_DIR="${INSTALL_DIR:-$(pwd)}"
SRC_DIR="$INSTALL_DIR/src/sylion-pipeline"
BACKUP_DIR="$INSTALL_DIR/.backup-$(date +%Y%m%d-%H%M%S)"

echo "==> SYLION Pipeline $VERSION — install"

# 1. Pre-flight
command -v python3 >/dev/null || { echo "ERROR: python3 wymagany"; exit 1; }
PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
case "$PY_VER" in
  3.11|3.12|3.13) ;;
  *) echo "ERROR: Python $PY_VER — wymagana 3.11/3.12/3.13"; exit 1 ;;
esac
echo "    [OK] Python $PY_VER"

# 2. Pre-clean — usuń pre-seeded DB z repo (auto-naprawa B-002)
FOUND_DBS=$(find "$SRC_DIR" -maxdepth 4 -type f \( -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' \) 2>/dev/null || true)
if [ -n "$FOUND_DBS" ]; then
  echo "    [CLEANUP] Usuwam pre-seeded DB ze źródła:"
  echo "$FOUND_DBS" | while IFS= read -r f; do
    echo "              rm $f"
    rm -f "$f"
  done
  # Also untrack from git if inside a repo
  if git -C "$INSTALL_DIR" rev-parse --git-dir >/dev/null 2>&1; then
    echo "$FOUND_DBS" | while IFS= read -r f; do
      git -C "$INSTALL_DIR" rm --cached --quiet "$f" 2>/dev/null || true
    done
  fi
fi

# 2b. Build guard (B-002) — żaden *.db / *.sqlite nie może być w źródle
if find "$SRC_DIR" -maxdepth 4 -type f \( -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' \) 2>/dev/null | grep -q .; then
  echo "ERROR: B-002 build guard — wykryto pre-seeded DB w źródle po cleanup. Paczka jest zepsuta."
  exit 2
fi
echo "    [OK] B-002 build guard"

# 3. Venv
if [ ! -d "$INSTALL_DIR/.venv" ]; then
  python3 -m venv "$INSTALL_DIR/.venv"
fi
# shellcheck disable=SC1091
source "$INSTALL_DIR/.venv/bin/activate"
echo "    [OK] venv"

# 4. Dependencies
if [ -f "$SRC_DIR/requirements.txt" ]; then
  pip install --quiet --upgrade pip
  pip install --quiet -r "$SRC_DIR/requirements.txt" || echo "    [WARN] requirements.txt install partial — kontynuuję"
  # SECURITY: upgrade python-dotenv (CVE-2026-28684)
  pip install --quiet --upgrade python-dotenv
fi
echo "    [OK] deps"

# 5. JWT secret (B-001) — generate if missing
ENV_FILE="$INSTALL_DIR/.env.generated"
if ! grep -q '^SYLION_JWT_SECRET=' "$ENV_FILE" 2>/dev/null; then
  SECRET=$(python3 -c 'import secrets; print(secrets.token_urlsafe(64))')
  {
    echo "# Auto-generated by SYLION v$VERSION installer at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "SYLION_JWT_SECRET=$SECRET"
    echo "SYLION_INTERNAL_API_KEY=$(python3 -c 'import secrets; print("internal_"+secrets.token_urlsafe(32))')"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "    [OK] B-001 JWT secret wygenerowany do $ENV_FILE"
else
  echo "    [OK] B-001 JWT secret już istnieje (zachowany)"
fi

# 6. VERSION file
echo "$VERSION" > "$SRC_DIR/VERSION"
echo "    [OK] VERSION=$VERSION"

# 7. DB init — tylko jeśli brak
DB_PATH="${SYLION_DB_PATH:-$INSTALL_DIR/sylion_aeis.db}"
if [ ! -f "$DB_PATH" ]; then
  mkdir -p "$(dirname "$DB_PATH")"
  touch "$DB_PATH"
  echo "    [OK] DB utworzona (pierwsze uruchomienie init_db() utworzy schemat)"
else
  echo "    [OK] DB istnieje — in-place upgrade (init_db idempotent)"
fi

# 8. Frontend deps + ensure start script is executable
chmod +x "$INSTALL_DIR/scripts/start_aeis.sh" 2>/dev/null || true
FRONTEND_DIR="$INSTALL_DIR/src/sylion-frontend"
if command -v node >/dev/null && command -v npm >/dev/null; then
  if [ -f "$FRONTEND_DIR/package.json" ]; then
    echo "    Installing frontend dependencies..."
    (cd "$FRONTEND_DIR" && npm install --silent 2>&1) || echo "    [WARN] npm install partial — kontynuuję"
    echo "    [OK] frontend deps"
  fi
else
  echo "    [SKIP] node/npm not found — frontend deps pominięte"
fi

# 9. Smoke
if command -v curl >/dev/null; then
  echo "==> Smoke test (opcjonalny, wymaga uruchomionego serwera)"
  if curl -s -m 2 http://127.0.0.1:8422/api/health 2>/dev/null | grep -q '6.2.0'; then
    echo "    [OK] serwer v6.2.0 odpowiada"
  else
    echo "    [INFO] serwer niewystartowany — zobacz INSTALL.md sekcja 'Uruchomienie lokalne'"
  fi
fi

cat <<EOF

==> Instalacja zakończona ✔

Uruchomienie (backend + frontend jedną komendą):
  ./scripts/start_aeis.sh

  • Backend:   http://127.0.0.1:8010
  • Frontend:  http://127.0.0.1:8422
  • Ctrl+C     zatrzymuje oba procesy naraz

Ręczne uruchomienie (tylko backend):
  source $ENV_FILE
  source $INSTALL_DIR/.venv/bin/activate
  cd $SRC_DIR
  SYLION_DB_PATH=$DB_PATH python3 -m sylion.server --host 127.0.0.1 --http-port 8422

Weryfikacja:  ./scripts/verify.sh
Rollback:     ./scripts/rollback.sh
Dokumentacja: README.md, INSTALL.md, CHANGELOG.md
EOF
