# =====================================================================
# SYLION Pipeline v6.2.0 installer (Windows PowerShell)
# Idempotentny - moze byc uruchomiony wielokrotnie
# Uruchomienie: .\scripts\install.ps1
# Jesli ExecutionPolicy blokuje:
#   powershell -ExecutionPolicy Bypass -File .\scripts\install.ps1
# =====================================================================

$ErrorActionPreference = "Stop"
$Version = "6.2.0"
$InstallDir = (Get-Location).Path
$SrcDir = Join-Path $InstallDir "src\sylion-pipeline"
$VenvDir = Join-Path $InstallDir ".venv"
$EnvFile = Join-Path $InstallDir ".env.generated"

Write-Host ""
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host " SYLION Pipeline $Version - Windows PowerShell install" -ForegroundColor Cyan
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "InstallDir: $InstallDir"
Write-Host "SrcDir:     $SrcDir"
Write-Host ""

function Find-Python {
    foreach ($cmd in @("python", "py -3", "python3")) {
        $parts = $cmd -split " "
        $exe = $parts[0]
        if (Get-Command $exe -ErrorAction SilentlyContinue) {
            return $cmd
        }
    }
    return $null
}

# --- 1. Detect Python ---
$PyCmd = Find-Python
if (-not $PyCmd) {
    Write-Host "[ERROR] Python nie znaleziony w PATH." -ForegroundColor Red
    Write-Host "        Zainstaluj Python 3.11/3.12/3.13 z https://www.python.org/downloads/" -ForegroundColor Red
    Write-Host "        Przy instalacji zaznacz 'Add Python to PATH'." -ForegroundColor Red
    exit 1
}
Write-Host "[1/8] Python wykryty: $PyCmd" -ForegroundColor Green

# --- 2. Check Python version ---
$verCheck = & cmd /c "$PyCmd -c `"import sys; assert sys.version_info >= (3,11)`" 2>&1"
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Wymagana Python 3.11+" -ForegroundColor Red
    & cmd /c "$PyCmd --version"
    exit 1
}
$verStr = & cmd /c "$PyCmd --version 2>&1"
Write-Host "[2/8] Python 3.11+ OK: $verStr" -ForegroundColor Green

# --- 3. B-002 build guard ---
$dbFound = Get-ChildItem -Path $SrcDir -Recurse -File -Include *.db, *.sqlite, *.sqlite3 -ErrorAction SilentlyContinue
if ($dbFound) {
    Write-Host "[ERROR] B-002 build guard - wykryto pre-seeded DB:" -ForegroundColor Red
    $dbFound | ForEach-Object { Write-Host "        $($_.FullName)" -ForegroundColor Red }
    exit 2
}
Write-Host "[3/8] B-002 build guard OK - zero pre-seeded DB" -ForegroundColor Green

# --- 4. Create venv ---
$activateScript = Join-Path $VenvDir "Scripts\Activate.ps1"
if (-not (Test-Path $activateScript)) {
    Write-Host "[4/8] Tworze venv w $VenvDir ..." -ForegroundColor Yellow
    & cmd /c "$PyCmd -m venv `"$VenvDir`""
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] Nie udalo sie utworzyc venv" -ForegroundColor Red
        exit 3
    }
} else {
    Write-Host "[4/8] venv juz istnieje - uzywam" -ForegroundColor Green
}

# --- 5. Activate venv ---
& $activateScript
Write-Host "[5/8] venv aktywny" -ForegroundColor Green

# --- 6. Install dependencies ---
$reqCandidates = @(
    (Join-Path $SrcDir "requirements.txt"),
    (Join-Path $SrcDir "requirements-lock.txt"),
    (Join-Path $SrcDir "dashboard\requirements.txt")
)
$reqFile = $reqCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1

if ($reqFile) {
    Write-Host "[6/8] Instaluje zaleznosci z $reqFile ..." -ForegroundColor Yellow
    python -m pip install --quiet --upgrade pip
    python -m pip install --quiet -r $reqFile
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[WARN] pip install zwrocil blad - kontynuuje" -ForegroundColor Yellow
    } else {
        Write-Host "[6/8] zaleznosci zainstalowane" -ForegroundColor Green
    }
} else {
    Write-Host "[6/8] brak requirements.txt - pomijam" -ForegroundColor Yellow
}

# --- 7. Generate JWT secret (B-001) ---
if (-not (Test-Path $EnvFile)) {
    $jwt = python -c "import secrets; print(secrets.token_urlsafe(64))"
    $internal = python -c "import secrets; print('internal_' + secrets.token_urlsafe(32))"
    $envContent = "# Auto-generated by SYLION v$Version installer at $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')`nSYLION_JWT_SECRET=$jwt`nSYLION_INTERNAL_API_KEY=$internal`n"
    [System.IO.File]::WriteAllText($EnvFile, $envContent)
    # Restrict ACL to current user
    try {
        $acl = Get-Acl $EnvFile
        $acl.SetAccessRuleProtection($true, $false)
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
            "FullControl", "Allow")
        $acl.AddAccessRule($rule)
        Set-Acl $EnvFile $acl
    } catch {
        Write-Host "[WARN] Nie udalo sie zrestryktowac ACL .env.generated" -ForegroundColor Yellow
    }
    Write-Host "[7/8] B-001 JWT secret wygenerowany do .env.generated" -ForegroundColor Green
} else {
    Write-Host "[7/8] B-001 JWT secret juz istnieje - zachowany" -ForegroundColor Green
}

# --- 8. VERSION file (no trailing space, no BOM, LF lineending) ---
[System.IO.File]::WriteAllText((Join-Path $SrcDir "VERSION"), $Version)
Write-Host "[8/8] VERSION=$Version zapisany" -ForegroundColor Green

# --- Smoke test ---
try {
    $resp = Invoke-WebRequest -Uri "http://127.0.0.1:8422/api/health" -TimeoutSec 2 -ErrorAction Stop
    if ($resp.Content -match "6\.2\.0") {
        Write-Host "      [SMOKE] serwer v6.2.0 juz dziala" -ForegroundColor Green
    }
} catch {
    # Server not running - OK
}

Write-Host ""
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host " Instalacja zakonczona sukcesem" -ForegroundColor Green
Write-Host "======================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Aby uruchomic serwer dev:"
Write-Host "  .\scripts\start-server.ps1" -ForegroundColor Yellow
Write-Host ""
Write-Host "Dokumentacja: README.md, INSTALL.md, CHANGELOG.md"
Write-Host "Weryfikacja:  .\scripts\verify.ps1"
Write-Host ""
