#!/usr/bin/env bash
# SYLION Pipeline v6.2.0 installer (Linux/Mac)
# Idempotentny — można uruchomić wielokrotnie bez efektów ubocznych.

set -euo pipefail

VERSION="6.2.0"
INSTALL_DIR="${INSTALL_DIR:-$(pwd)}"
SRC_DIR="$INSTALL_DIR/src/sylion-pipeline"
BACKUP_DIR="$INSTALL_DIR/.backup-$(date +%Y%m%d-%H%M%S)"

echo "==> SYLION Pipeline $VERSION — install"

# 1. Pre-flight
command -v python3 >/dev/null || { echo "ERROR: python3 wymagany"; exit 1; }
PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
case "$PY_VER" in
  3.11|3.12|3.13) ;;
  *) echo "ERROR: Python $PY_VER — wymagana 3.11/3.12/3.13"; exit 1 ;;
esac
echo "    [OK] Python $PY_VER"

# 2. Build guard (B-002) — żaden *.db / *.sqlite nie może być w źródle
if find "$SRC_DIR" -maxdepth 4 -type f \( -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' \) 2>/dev/null | grep -q .; then
  echo "ERROR: B-002 build guard — wykryto pre-seeded DB w źródle. Paczka jest zepsuta."
  exit 2
fi
echo "    [OK] B-002 build guard"

# 3. Venv
if [ ! -d "$INSTALL_DIR/.venv" ]; then
  python3 -m venv "$INSTALL_DIR/.venv"
fi
# shellcheck disable=SC1091
source "$INSTALL_DIR/.venv/bin/activate"
echo "    [OK] venv"

# 4. Dependencies
if [ -f "$SRC_DIR/requirements.txt" ]; then
  pip install --quiet --upgrade pip
  pip install --quiet -r "$SRC_DIR/requirements.txt" || echo "    [WARN] requirements.txt install partial — kontynuuję"
fi
echo "    [OK] deps"

# 5. JWT secret (B-001) — generate if missing
ENV_FILE="$INSTALL_DIR/.env.generated"
if ! grep -q '^SYLION_JWT_SECRET=' "$ENV_FILE" 2>/dev/null; then
  SECRET=$(python3 -c 'import secrets; print(secrets.token_urlsafe(64))')
  {
    echo "# Auto-generated by SYLION v$VERSION installer at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "SYLION_JWT_SECRET=$SECRET"
    echo "SYLION_INTERNAL_API_KEY=$(python3 -c 'import secrets; print("internal_"+secrets.token_urlsafe(32))')"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "    [OK] B-001 JWT secret wygenerowany do $ENV_FILE"
else
  echo "    [OK] B-001 JWT secret już istnieje (zachowany)"
fi

# 6. VERSION file
echo "$VERSION" > "$SRC_DIR/VERSION"
echo "    [OK] VERSION=$VERSION"

# 7. DB init — tylko jeśli brak
DB_PATH="${SYLION_DB_PATH:-$INSTALL_DIR/sylion_aeis.db}"
if [ ! -f "$DB_PATH" ]; then
  mkdir -p "$(dirname "$DB_PATH")"
  touch "$DB_PATH"
  echo "    [OK] DB utworzona (pierwsze uruchomienie init_db() utworzy schemat)"
else
  echo "    [OK] DB istnieje — in-place upgrade (init_db idempotent)"
fi

# 8. Smoke
if command -v curl >/dev/null; then
  echo "==> Smoke test (opcjonalny, wymaga uruchomionego serwera)"
  if curl -s -m 2 http://127.0.0.1:8422/api/health 2>/dev/null | grep -q '6.2.0'; then
    echo "    [OK] serwer v6.2.0 odpowiada"
  else
    echo "    [INFO] serwer niewystartowany — zobacz INSTALL.md sekcja 'Uruchomienie lokalne'"
  fi
fi

cat <<EOF

==> Instalacja zakończona

Następne kroki:
  1. source $ENV_FILE
  2. source $INSTALL_DIR/.venv/bin/activate
  3. cd $SRC_DIR
  4. SYLION_DB_PATH=$DB_PATH python3 -m sylion.server --host 127.0.0.1 --http-port 8422

Weryfikacja:  ./scripts/verify.sh
Rollback:     ./scripts/rollback.sh
Dokumentacja: README.md, INSTALL.md, CHANGELOG.md
EOF
