@echo off
REM =====================================================================
REM SYLION Pipeline v6.2.0 installer (Windows CMD)
REM Idempotentny - moze byc uruchomiony wielokrotnie
REM =====================================================================
setlocal

set "VERSION=6.2.0"
set "INSTALL_DIR=%cd%"
set "SRC_DIR=%INSTALL_DIR%\src\sylion-pipeline"
set "VENV_DIR=%INSTALL_DIR%\.venv"
set "ENV_FILE=%INSTALL_DIR%\.env.generated"

echo.
echo ======================================================
echo  SYLION Pipeline %VERSION% - Windows install
echo ======================================================
echo.
echo INSTALL_DIR: %INSTALL_DIR%
echo SRC_DIR:     %SRC_DIR%
echo.

REM --- 1. Detect Python (try python, py -3, python3) ---
set "PY_CMD="
where python >nul 2>&1 && set "PY_CMD=python"
if "%PY_CMD%"=="" where py >nul 2>&1 && set "PY_CMD=py -3"
if "%PY_CMD%"=="" where python3 >nul 2>&1 && set "PY_CMD=python3"
if "%PY_CMD%"=="" (
  echo [ERROR] Python nie znaleziony w PATH.
  echo         Zainstaluj Python 3.11/3.12/3.13 z https://www.python.org/downloads/
  echo         Przy instalacji zaznacz "Add Python to PATH".
  exit /b 1
)
echo [1/8] Python wykryty: %PY_CMD%

REM --- 2. Check Python version ---
%PY_CMD% -c "import sys; assert sys.version_info >= (3,11), f'Got {sys.version_info}'" 2>nul
if errorlevel 1 (
  echo [ERROR] Wymagana Python 3.11+. Wykryta wersja niewlasciwa.
  %PY_CMD% --version
  exit /b 1
)
echo [2/8] Python 3.11+ OK
%PY_CMD% --version

REM --- 3. B-002 build guard: zero *.db in src ---
set "FOUND_DB="
for /f "delims=" %%F in ('dir /s /b "%SRC_DIR%\*.db" "%SRC_DIR%\*.sqlite" "%SRC_DIR%\*.sqlite3" 2^>nul') do set "FOUND_DB=%%F"
if defined FOUND_DB (
  echo [ERROR] B-002 build guard - wykryto pre-seeded DB w zrodle:
  echo         %FOUND_DB%
  echo         Paczka jest uszkodzona. Sciagnij ponownie.
  exit /b 2
)
echo [3/8] B-002 build guard OK - zero pre-seeded DB

REM --- 4. Create venv ---
if not exist "%VENV_DIR%\Scripts\activate.bat" (
  echo [4/8] Tworze venv w %VENV_DIR% ...
  %PY_CMD% -m venv "%VENV_DIR%"
  if errorlevel 1 (
    echo [ERROR] Nie udalo sie utworzyc venv. Sprawdz prawa zapisu.
    exit /b 3
  )
) else (
  echo [4/8] venv juz istnieje - uzywam
)

REM --- 5. Activate venv ---
call "%VENV_DIR%\Scripts\activate.bat"
if errorlevel 1 (
  echo [ERROR] Nie udalo sie aktywowac venv.
  exit /b 3
)
echo [5/8] venv aktywny

REM --- 6. Install dependencies ---
set "REQ_FILE=%SRC_DIR%\requirements.txt"
if not exist "%REQ_FILE%" set "REQ_FILE=%SRC_DIR%\requirements-lock.txt"
if not exist "%REQ_FILE%" set "REQ_FILE=%SRC_DIR%\dashboard\requirements.txt"

if exist "%REQ_FILE%" (
  echo [6/8] Instaluje zaleznosci z %REQ_FILE% ...
  python -m pip install --quiet --upgrade pip
  python -m pip install --quiet -r "%REQ_FILE%"
  if errorlevel 1 (
    echo [WARN] pip install zwrocil blad. Niektore pakiety moga byc niedostepne.
    echo         Kontynuuje - mozesz je doinstalowac recznie.
  ) else (
    echo [6/8] zaleznosci zainstalowane
  )
) else (
  echo [6/8] brak requirements.txt - pomijam
)

REM --- 7. Generate JWT secret (B-001) ---
if not exist "%ENV_FILE%" (
  python -c "import secrets; j=secrets.token_urlsafe(64); k='internal_'+secrets.token_urlsafe(32); open(r'%ENV_FILE%','w',newline='\n').write('# Auto-generated by SYLION v%VERSION% installer\nSYLION_JWT_SECRET='+j+'\nSYLION_INTERNAL_API_KEY='+k+'\n')"
  if errorlevel 1 (
    echo [ERROR] Nie udalo sie wygenerowac .env.generated
    exit /b 4
  )
  echo [7/8] B-001 JWT secret wygenerowany do .env.generated
) else (
  echo [7/8] B-001 JWT secret juz istnieje - zachowany
)

REM --- 8. Write VERSION file (no trailing space, no BOM) ---
python -c "open(r'%SRC_DIR%\VERSION','w',newline='\n').write('%VERSION%')"
echo [8/8] VERSION=%VERSION% zapisany

REM --- Smoke test (optional) ---
where curl >nul 2>&1
if not errorlevel 1 (
  curl -s -m 2 http://127.0.0.1:8422/api/health 2>nul | findstr "6.2.0" >nul 2>&1
  if not errorlevel 1 (
    echo       [SMOKE] serwer v6.2.0 juz dziala na 127.0.0.1:8422
  )
)

echo.
echo ======================================================
echo  Instalacja zakonczona sukcesem
echo ======================================================
echo.
echo Aby uruchomic serwer dev:
echo.
echo   scripts\start-server.bat
echo.
echo Dokumentacja: README.md, INSTALL.md, CHANGELOG.md
echo Weryfikacja:  scripts\verify.bat
echo.
endlocal
exit /b 0
