# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import actions_pb2 as actions__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in actions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleAction = channel.unary_unary(
                '/sylion.aeis.advisor.actions.v1.ActionsService/HandleAction',
                request_serializer=actions__pb2.HandleActionRequest.SerializeToString,
                response_deserializer=actions__pb2.HandleActionResponse.FromString,
                _registered_method=True)
        self.RetryFailed = channel.unary_unary(
                '/sylion.aeis.advisor.actions.v1.ActionsService/RetryFailed',
                request_serializer=actions__pb2.RetryFailedRequest.SerializeToString,
                response_deserializer=actions__pb2.RetryFailedResponse.FromString,
                _registered_method=True)
        self.GetRoutingAudit = channel.unary_unary(
                '/sylion.aeis.advisor.actions.v1.ActionsService/GetRoutingAudit',
                request_serializer=actions__pb2.GetRoutingAuditRequest.SerializeToString,
                response_deserializer=actions__pb2.GetRoutingAuditResponse.FromString,
                _registered_method=True)


class ActionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryFailed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutingAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleAction': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleAction,
                    request_deserializer=actions__pb2.HandleActionRequest.FromString,
                    response_serializer=actions__pb2.HandleActionResponse.SerializeToString,
            ),
            'RetryFailed': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryFailed,
                    request_deserializer=actions__pb2.RetryFailedRequest.FromString,
                    response_serializer=actions__pb2.RetryFailedResponse.SerializeToString,
            ),
            'GetRoutingAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingAudit,
                    request_deserializer=actions__pb2.GetRoutingAuditRequest.FromString,
                    response_serializer=actions__pb2.GetRoutingAuditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.aeis.advisor.actions.v1.ActionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.aeis.advisor.actions.v1.ActionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.actions.v1.ActionsService/HandleAction',
            actions__pb2.HandleActionRequest.SerializeToString,
            actions__pb2.HandleActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryFailed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.actions.v1.ActionsService/RetryFailed',
            actions__pb2.RetryFailedRequest.SerializeToString,
            actions__pb2.RetryFailedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoutingAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.actions.v1.ActionsService/GetRoutingAudit',
            actions__pb2.GetRoutingAuditRequest.SerializeToString,
            actions__pb2.GetRoutingAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
