# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import preferences_pb2 as preferences__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in preferences_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreferencesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEffective = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetEffective',
                request_serializer=preferences__pb2.GetEffectiveRequest.SerializeToString,
                response_deserializer=preferences__pb2.PreferenceValue.FromString,
                _registered_method=True)
        self.GetExplicit = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetExplicit',
                request_serializer=preferences__pb2.GetExplicitRequest.SerializeToString,
                response_deserializer=preferences__pb2.PreferenceValue.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/Set',
                request_serializer=preferences__pb2.SetRequest.SerializeToString,
                response_deserializer=preferences__pb2.SetResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/Reset',
                request_serializer=preferences__pb2.ResetRequest.SerializeToString,
                response_deserializer=preferences__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Disable = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/Disable',
                request_serializer=preferences__pb2.DisableRequest.SerializeToString,
                response_deserializer=preferences__pb2.DisableResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/List',
                request_serializer=preferences__pb2.ListRequest.SerializeToString,
                response_deserializer=preferences__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetAudit = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetAudit',
                request_serializer=preferences__pb2.GetAuditRequest.SerializeToString,
                response_deserializer=preferences__pb2.GetAuditResponse.FromString,
                _registered_method=True)
        self.SoftLearningTick = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/SoftLearningTick',
                request_serializer=preferences__pb2.SoftLearningTickRequest.SerializeToString,
                response_deserializer=preferences__pb2.SoftLearningTickResponse.FromString,
                _registered_method=True)
        self.RequestHardChange = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/RequestHardChange',
                request_serializer=preferences__pb2.RequestHardChangeRequest.SerializeToString,
                response_deserializer=preferences__pb2.RequestHardChangeResponse.FromString,
                _registered_method=True)
        self.ConfirmHardChange = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/ConfirmHardChange',
                request_serializer=preferences__pb2.ConfirmHardChangeRequest.SerializeToString,
                response_deserializer=preferences__pb2.ConfirmHardChangeResponse.FromString,
                _registered_method=True)
        self.GetCatalog = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetCatalog',
                request_serializer=preferences__pb2.GetCatalogRequest.SerializeToString,
                response_deserializer=preferences__pb2.GetCatalogResponse.FromString,
                _registered_method=True)
        self.AddCustomCatalogEntry = channel.unary_unary(
                '/sylion.aeis.advisor.preferences.v1.PreferencesService/AddCustomCatalogEntry',
                request_serializer=preferences__pb2.AddCustomCatalogEntryRequest.SerializeToString,
                response_deserializer=preferences__pb2.AddCustomCatalogEntryResponse.FromString,
                _registered_method=True)


class PreferencesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEffective(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExplicit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SoftLearningTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestHardChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmHardChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCustomCatalogEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreferencesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEffective': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEffective,
                    request_deserializer=preferences__pb2.GetEffectiveRequest.FromString,
                    response_serializer=preferences__pb2.PreferenceValue.SerializeToString,
            ),
            'GetExplicit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExplicit,
                    request_deserializer=preferences__pb2.GetExplicitRequest.FromString,
                    response_serializer=preferences__pb2.PreferenceValue.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=preferences__pb2.SetRequest.FromString,
                    response_serializer=preferences__pb2.SetResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=preferences__pb2.ResetRequest.FromString,
                    response_serializer=preferences__pb2.ResetResponse.SerializeToString,
            ),
            'Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.Disable,
                    request_deserializer=preferences__pb2.DisableRequest.FromString,
                    response_serializer=preferences__pb2.DisableResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=preferences__pb2.ListRequest.FromString,
                    response_serializer=preferences__pb2.ListResponse.SerializeToString,
            ),
            'GetAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudit,
                    request_deserializer=preferences__pb2.GetAuditRequest.FromString,
                    response_serializer=preferences__pb2.GetAuditResponse.SerializeToString,
            ),
            'SoftLearningTick': grpc.unary_unary_rpc_method_handler(
                    servicer.SoftLearningTick,
                    request_deserializer=preferences__pb2.SoftLearningTickRequest.FromString,
                    response_serializer=preferences__pb2.SoftLearningTickResponse.SerializeToString,
            ),
            'RequestHardChange': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestHardChange,
                    request_deserializer=preferences__pb2.RequestHardChangeRequest.FromString,
                    response_serializer=preferences__pb2.RequestHardChangeResponse.SerializeToString,
            ),
            'ConfirmHardChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmHardChange,
                    request_deserializer=preferences__pb2.ConfirmHardChangeRequest.FromString,
                    response_serializer=preferences__pb2.ConfirmHardChangeResponse.SerializeToString,
            ),
            'GetCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalog,
                    request_deserializer=preferences__pb2.GetCatalogRequest.FromString,
                    response_serializer=preferences__pb2.GetCatalogResponse.SerializeToString,
            ),
            'AddCustomCatalogEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomCatalogEntry,
                    request_deserializer=preferences__pb2.AddCustomCatalogEntryRequest.FromString,
                    response_serializer=preferences__pb2.AddCustomCatalogEntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.aeis.advisor.preferences.v1.PreferencesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.aeis.advisor.preferences.v1.PreferencesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreferencesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEffective(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetEffective',
            preferences__pb2.GetEffectiveRequest.SerializeToString,
            preferences__pb2.PreferenceValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExplicit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetExplicit',
            preferences__pb2.GetExplicitRequest.SerializeToString,
            preferences__pb2.PreferenceValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/Set',
            preferences__pb2.SetRequest.SerializeToString,
            preferences__pb2.SetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/Reset',
            preferences__pb2.ResetRequest.SerializeToString,
            preferences__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/Disable',
            preferences__pb2.DisableRequest.SerializeToString,
            preferences__pb2.DisableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/List',
            preferences__pb2.ListRequest.SerializeToString,
            preferences__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetAudit',
            preferences__pb2.GetAuditRequest.SerializeToString,
            preferences__pb2.GetAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SoftLearningTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/SoftLearningTick',
            preferences__pb2.SoftLearningTickRequest.SerializeToString,
            preferences__pb2.SoftLearningTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestHardChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/RequestHardChange',
            preferences__pb2.RequestHardChangeRequest.SerializeToString,
            preferences__pb2.RequestHardChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmHardChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/ConfirmHardChange',
            preferences__pb2.ConfirmHardChangeRequest.SerializeToString,
            preferences__pb2.ConfirmHardChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/GetCatalog',
            preferences__pb2.GetCatalogRequest.SerializeToString,
            preferences__pb2.GetCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCustomCatalogEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.preferences.v1.PreferencesService/AddCustomCatalogEntry',
            preferences__pb2.AddCustomCatalogEntryRequest.SerializeToString,
            preferences__pb2.AddCustomCatalogEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
