# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pricing_pb2 as pricing__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pricing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PricingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCost = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/GetCost',
                request_serializer=pricing__pb2.GetCostRequest.SerializeToString,
                response_deserializer=pricing__pb2.CostEstimate.FromString,
                _registered_method=True)
        self.RefreshPricing = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/RefreshPricing',
                request_serializer=pricing__pb2.RefreshPricingRequest.SerializeToString,
                response_deserializer=pricing__pb2.RefreshPricingResponse.FromString,
                _registered_method=True)
        self.ListProviders = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/ListProviders',
                request_serializer=pricing__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=pricing__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/ListModels',
                request_serializer=pricing__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=pricing__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.RegisterAdapter = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/RegisterAdapter',
                request_serializer=pricing__pb2.RegisterAdapterRequest.SerializeToString,
                response_deserializer=pricing__pb2.RegisterAdapterResponse.FromString,
                _registered_method=True)
        self.GetPricingHistory = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/GetPricingHistory',
                request_serializer=pricing__pb2.GetPricingHistoryRequest.SerializeToString,
                response_deserializer=pricing__pb2.GetPricingHistoryResponse.FromString,
                _registered_method=True)
        self.GetProvider = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/GetProvider',
                request_serializer=pricing__pb2.GetProviderRequest.SerializeToString,
                response_deserializer=pricing__pb2.Provider.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/sylion.aeis.advisor.pricing.v1.PricingService/GetModel',
                request_serializer=pricing__pb2.GetModelRequest.SerializeToString,
                response_deserializer=pricing__pb2.Model.FromString,
                _registered_method=True)


class PricingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshPricing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPricingHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCost,
                    request_deserializer=pricing__pb2.GetCostRequest.FromString,
                    response_serializer=pricing__pb2.CostEstimate.SerializeToString,
            ),
            'RefreshPricing': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshPricing,
                    request_deserializer=pricing__pb2.RefreshPricingRequest.FromString,
                    response_serializer=pricing__pb2.RefreshPricingResponse.SerializeToString,
            ),
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=pricing__pb2.ListProvidersRequest.FromString,
                    response_serializer=pricing__pb2.ListProvidersResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=pricing__pb2.ListModelsRequest.FromString,
                    response_serializer=pricing__pb2.ListModelsResponse.SerializeToString,
            ),
            'RegisterAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAdapter,
                    request_deserializer=pricing__pb2.RegisterAdapterRequest.FromString,
                    response_serializer=pricing__pb2.RegisterAdapterResponse.SerializeToString,
            ),
            'GetPricingHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPricingHistory,
                    request_deserializer=pricing__pb2.GetPricingHistoryRequest.FromString,
                    response_serializer=pricing__pb2.GetPricingHistoryResponse.SerializeToString,
            ),
            'GetProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProvider,
                    request_deserializer=pricing__pb2.GetProviderRequest.FromString,
                    response_serializer=pricing__pb2.Provider.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=pricing__pb2.GetModelRequest.FromString,
                    response_serializer=pricing__pb2.Model.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sylion.aeis.advisor.pricing.v1.PricingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sylion.aeis.advisor.pricing.v1.PricingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PricingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/GetCost',
            pricing__pb2.GetCostRequest.SerializeToString,
            pricing__pb2.CostEstimate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshPricing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/RefreshPricing',
            pricing__pb2.RefreshPricingRequest.SerializeToString,
            pricing__pb2.RefreshPricingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/ListProviders',
            pricing__pb2.ListProvidersRequest.SerializeToString,
            pricing__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/ListModels',
            pricing__pb2.ListModelsRequest.SerializeToString,
            pricing__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/RegisterAdapter',
            pricing__pb2.RegisterAdapterRequest.SerializeToString,
            pricing__pb2.RegisterAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPricingHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/GetPricingHistory',
            pricing__pb2.GetPricingHistoryRequest.SerializeToString,
            pricing__pb2.GetPricingHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/GetProvider',
            pricing__pb2.GetProviderRequest.SerializeToString,
            pricing__pb2.Provider.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sylion.aeis.advisor.pricing.v1.PricingService/GetModel',
            pricing__pb2.GetModelRequest.SerializeToString,
            pricing__pb2.Model.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
